### ISSUE TITLE
vmtkcenterlines operates differently based on scaling

### ISSUE THREAD

**Issue by oyvinev** [vmtk/vmtk#107]
I have two equal surfaces, one scaled to millimeters and one scaled to meters (http://folk.uio.no/oyvinev/vmtk/).

When trying to use vmtkcenterlines on them, it works fine on the millimeter surface, but fails on the surface scaled to meters, with the following error message:

> vmtkcenterlines -ifile model_m.vtp -seedselector openprofiles
> ...
> Computing centerlines...ERROR: In /home/oyvinev/repositories/vmtk/vtkVmtk/ComputationalGeometry/vtkvmtkSteepestDescentLineTracer.cxx, line 338
> vtkvmtkSteepestDescentLineTracer (0x294a1b0): Seed id invalid or exceeds input number of points.
> ...

**Comment by lassoan** [comment]
Closing this issue due to long time of inactivity and link to sample data set not being valid anymore.
