### ISSUE TITLE
VTK not found

### ISSUE THREAD

**Issue by simplementegolf** [vmtk/vmtk#136]
I'm using system's VTK, vmtk's commit 24f5dc507b857cd1a201f82753af13954dac6097.
The following command crashes:
cd /home/leandro/codes/vmtk-build/VMTK-Build && /usr/bin/cmake -DBUILDNAME:STRING= -DSITE:STRING= -DMAKECOMMAND:STRING= -DCMAKE_CXX_COMPILER:STRING=/usr/bin/c++ -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_EXAMPLES:BOOL= -DBUILD_TESTING:BOOL= -DBUILD_DOCUMENTATION:BOOL= "-DCMAKE_SHARED_LINKER_FLAGS:STRING= " "-DCMAKE_EXE_LINKER_FLAGS:STRING= " -DCMAKE_OSX_ARCHITECTURES:STRING= -DCMAKE_CXX_FLAGS:STRING= -DCMAKE_C_FLAGS:STRING= -DCMAKE_INSTALL_PREFIX:PATH=/home/leandro/codes/vmtk-build/Install -DVTK_VMTK_WRAP_PYTHON:BOOL=ON -DVMTK_USE_SUPERBUILD:BOOL=OFF -DVMTK_CONTRIB_SCRIPTS:BOOL=ON -DVTK_VMTK_CONTRIB:BOOL=ON -DVMTK_SCRIPTS_ENABLED:BOOL=ON -DVMTK_MINIMAL_INSTALL:BOOL=OFF -DVMTK_ENABLE_DISTRIBUTION:BOOL=OFF -DVMTK_WITH_LIBRARY_VERSION:BOOL=OFF -DVMTK_BUILD_TETGEN:BOOL=ON -DVTK_VMTK_USE_COCOA:BOOL= -DVMTK_BUILD_STREAMTRACER:BOOL=ON -DVTK_REQUIRED_OBJCXX_FLAGS:STRING= -DITK_DIR:PATH=/home/leandro/codes/vmtk-build/ITK-Build -DVTK_DIR:PATH=/usr/lib/cmake/vtk-6.1 -DCMAKE_RC_COMPILER:BOOL= -DPYTHON_DEBUG_LIBRARY= -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.4m.so "-GUnix Makefiles" /home/leandro/codes/vmtk
CMake Error at /usr/share/cmake-2.8/Modules/FindVTK.cmake:135 (message):
  VTK not found.  Set the VTK_DIR cmake cache entry to the directory
  containing VTKConfig.cmake.  This is either the root of the build tree, or
  PREFIX/lib/vtk for an installation.  For VTK 4.0, this is the location of
  UseVTK.cmake.  This is either the root of the build tree or
  PREFIX/include/vtk for an installation.
Call Stack (most recent call first):
  vtkVmtk/Utilities/vtkvmtkITK/CMakeLists.txt:13 (find_package)

I think that the arguments are wrong, particularly the quotes.
VMTK-Build/CMakeCache.txt has the following line:
VTK_DIR:PATH=VTK_DIR-NOTFOUND

**Comment by simplementegolf** [comment]
I found the issue. If the VTK major version is greater than 5, it looks for 6.2. There are a bunch of vtkVmtk/*/CMakeList.txt that have a find_package(VTK 6.2 .....)
I have VTK version 6.1. If any 6.x works, 6.2 should not be explicitly required.

**Comment by lantiga** [comment]
Thanks for pointing this out, we'll take this into account when finalizing the VTK 6 port.

**Comment by lantiga** [comment]
Should be solved now.
