### ISSUE TITLE
vtkCommonPython

### ISSUE THREAD

**Issue by johnwog** [vmtk/vmtk#137]
Hi 

I am running Yosemite
I have Canopy installed as my python distribution

I am trying to run vmtk and I keep getting the following error

from vmtk import vmtkscripts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vmtk-1.2-py2.7-macosx-10.9-intel.egg/vmtk/vmtkscripts.py", line 137, in <module>
    exec('from '+item+' import *')
  File "<string>", line 1, in <module>
  File "/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vmtk-1.2-py2.7-macosx-10.9-intel.egg/vmtk/vmtkactivetubes.py", line 18, in <module>
    import vtk
  File "/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vmtk-1.2-py2.7-macosx-10.9-intel.egg/vmtk/vtk/__init__.py", line 41, in <module>
    from vtkCommonPython import *

Any hints on where the issue is ?

Thanks!

**Comment by daron1337** [comment]
Hi,
it could be a problem of environment variables.
Could you please post output of:

echo $PATH
echo $PYTHONPATH
echo $DYLD_LIBRARY_PATH

**Comment by johnwog** [comment]
Here you are

echo $PATH
/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vmtk-1.2-py2.7-macosx-10.9-intel.egg/vmtk/bin:/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin

echo $PYTHONPATH
/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vmtk-1.2-py2.7-macosx-10.9-intel.egg/vmtk/lib:/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vmtk-1.2-py2.7-macosx-10.9-intel.egg/vmtk:/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/bin::/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/bin

echo $DYLD_LIBRARY_PATH
/Users/ioannisvogiatzisoikonomidis/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vmtk-1.2-py2.7-macosx-10.9-intel.egg/vmtk/lib:

**Comment by daron1337** [comment]
Do you have other versions of vtk installed in your system?

**Comment by johnwog** [comment]
I have canopy as my python distribution and it has a vtk package
I also have paraview which has a vtk package

**Comment by daron1337** [comment]
Ok, that's the problem. VMTK uses its own VTK version.
Possible solutions: 
 - Find a way to hide the canopy vtk from vmtk
 - Install a new python in an isolated virtual environment https://virtualenv.pypa.io/en/latest/ and then install vmtk here ( suggested )

**Comment by johnwog** [comment]
can I recompile vmtk using my installed version of vtk like i can do with SimpleITK for example?

**Comment by daron1337** [comment]
No, the VTK used in VMTK is a patched version of VTK.

**Comment by johnwog** [comment]
thanks for your help
