### ISSUE TITLE
Unable to build "vtkvmtkMisc" with VTK 6.2.x (LNK2001: unresolved external symbol)

### ISSUE THREAD

**Issue by prilepin** [vmtk/vmtk#138]
I try to build VMTK from the latest [revision](https://github.com/vmtk/vmtk/commit/24f5dc507b857cd1a201f82753af13954dac6097) in VS2012 with the latest VTK (6.2.x) and ITK (4.7.x) libraries. I'm getting an error while building module `vtkvmtkMisc`.

```
Creating library D:/B/VMTK/VMTK-Build/bin/Release/vtkvmtkMisc.lib and object D:/B/VMTK/VMTK-Build/bin/Release/vtkvmtkMisc.exp
1>vtkvmtkStaticTemporalInterpolatedVelocityField.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl vtkvmtkStaticTemporalInterpolatedVelocityField::SetLastCellId(__int64,int)" (?SetLastCellId@vtkvmtkStaticTemporalInterpolatedVelocityField@@UEAAX_JH@Z) [D:\B\VMTK\VMTK-Build\vtkVmtk\Misc\vtkvmtkMisc.vcxproj]
1>D:\B\VMTK\VMTK-Build\bin\Release\vtkvmtkMisc.dll : fatal error LNK1120: 1 unresolved externals [D:\B\VMTK\VMTK-Build\vtkVmtk\Misc\vtkvmtkMisc.vcxproj]
```

How is it possible to build VMTK with VTK 6.2.x?

**Comment by lantiga** [comment]
I just committed a fix that solves this, but you'll find issues in the Python part at runtime.
We're still working on finishing the port to VTK 6. It shouldn't take long - we have active internal projects that depend on this.

**Comment by prilepin** [comment]
@lantiga thank you for your answer and the fix for that bug. I have been planning to use only C++ classes from VMTK in my project.
