### ISSUE TITLE
No module named libvtkvmtkCommonPython

### ISSUE THREAD

**Issue by mtisdall** [vmtk/vmtk#149]
I am trying to build vmtk from source on Centos7.
The build seems to go fine - makelogfile attached - but when I try to run a command I get the error
'No module named libvtkvmtkCommonPython'
All my paths seems fine and there is a file in vmtk named libvtkvmtkCommonPythonD.so but nothing called libvtkvmtkCommonPython.
My linux skills are quite basic so would really appreciate some help but please take me through step by step!
Thanks

**Comment by lantiga** [comment]
I don't have experience with Centos, but essentially there are two libvtkvmtkCommonPython
- libvtkvmtkCommonPythonD.so, which is a shared library, which should be in your LD_LIBRARY_PATH
- libvtkvmtkCommonPython.so (it has a .so extension on linux if I remember well) which is a python module, which should be in your PYTHONPATH
If the build went well, you should find the latter under vmtk-build/Install/lib/vmtk/vmtk

Feel free to post your env variables and the content of Install/lib/vmtk/vmtk.

**Comment by mtisdall** [comment]
I think I got it sorted.
I had multiple versions of Python and so I removed everything and rebuilt from source.
Seems to be working fine now
Thanks
Martin

**Comment by lantiga** [comment]
Great, thanks for letting me know.
