### ISSUE TITLE
No module named vtkvmtkRenderingPython

### ISSUE THREAD

**Issue by leandrogryn** [vmtk/vmtk#151]
I installed VMTK from source (pulled from github master-branch yesterday).
I use system wide VTK (6.1), but not ITK.

When I try to run anything or import a library, I get:
ImportError: No module named vtkvmtkRenderingPython

Other 4 modules should be getting imported, and they are fine, but I can't even find the library file vtkvmtkRenderingPython.so.

Is there something I'm missing?
Is there a configuration that I need to set in cmake? (I've tried many combinations with no luck)

I didn't have problems installing VMTK from the Ubuntu repository, but when I updated from VTK 5.x to VTK 6.x, the VMTK in the repo broke. So I had to switch to installing from source, but I run into the issue mentioned above.

I'll appreciate any suggestion.

**Comment by lantiga** [comment]
You can find a branch that compiles against VTK 6.x here https://github.com/vmtk/vmtk/tree/vtk6
However, there are a few issues with vtkITK filters under Segmentation that I'm still ironing out.

**Comment by leandrogryn** [comment]
A lot of CMakeList.txt inside vtkVmtk and its subdirectories have "find_package(VTK 6.2 ....".
This fails in my case, where I have VTK 6.1. I didn't test if removing .2 will actually look for 6.x, but it should.

**Comment by lantiga** [comment]
Fixed.
