### ISSUE TITLE
How to install vmtk in anaconda python2.7 at mac OSX

### ISSUE THREAD

**Issue by zxh2135645** [vmtk/vmtk#167]
Hi,

So far I installed anaconda but there is no vmtk available for mac in anaconda. Can anyone help me with this issue? I will really appreciate it.

Thanks,
James

**Comment by rizzol** [comment]
Hi James, 

This is something I'd be interested in putting together once we finalize the support for python 3. Do you have any experience building packages for the anaconda distribution? 

I'm thinking it would be best to use [conda-forge ](https://github.com/conda-forge/staged-recipes) as they have a pretty good system in place. Of the two main requirements (VTK and ITK), conda-forge already support VTK7. The bulk of the work would be packaging ITK as it is currently distributed as binaries (if not building from source). I'd love to hear your thoughts. 

-Rick

**Comment by zxh2135645** [comment]
Hi Rick,

I do not have experience in building packages for anaconda distribution. But I'm glad to learn it since this could be a good experience for me and also benefit people who had the same issue as I did. I was trying to understand "packaging ITK as it's currently distributed as binaries". Can you explain a bit more of it to me?

Thanks,
James

**Comment by rlizzo** [comment]
Hey @zxh2135645 ,

All I was referring to is that you need to package the ITK and VTK binaries in a way that will allow them to link to the vmtk Python code. It's covered in detail in a few of the anaconda build docs. I'm fully supportive of you giving this a shot. How should we work together on this?

**Comment by rlizzo** [comment]
I'm closing this issue to move discussion to a more general issue topic for anaconda support. Please see https://github.com/vmtk/vmtk/issues/176
