### ISSUE TITLE
Package for Anaconda Distribution

### ISSUE THREAD

**Issue by rlizzo** [vmtk/vmtk#176]
This is a new topic to discuss issues related to creating an anaconda distribution for VMTK (following from closed out issue https://github.com/vmtk/vmtk/issues/167)

@lantiga can you please create an official vmtk anaconda cloud account at https://anaconda.org and give me access? my anaconda cloud username is rlizzo (https://anaconda.org/rlizzo). 

I'll get working on creating a distribution with conda-build following the tutorials at https://conda.io/docs/build_tutorials.html . Will create a new pull request when I have something worth sharing/discussing.

**Comment by lantiga** [comment]
Done! Let me know as you make progress, I'll gladly take this opportunity to learn about conda builds.

**Comment by rlizzo** [comment]
Hey luca, 

So I think I've got everything working for anaconda packaging on the linux front. Take a look at the anaconda branch in the repo. I uploaded a few test builds (using python versions 2.7, 3.3, 3.4, 3.5, & 3.6 to the vmtk anaconda cloud organization under the label "dev". To try and install them just run 

`conda install --channel https://conda.anaconda.org/vmtk/label/dev vmtk`

The biggest challenges I faced was the non-standard way that cmake is set up to perform the install. instead of the common two command paradigm `make`, `make install` conda-build expects, vmtk only uses the `make` command and stores the results in the Install directory. Since conda-build wasn't aware of this directory being created, it didn't automatically transfer the files. In order to get around this I had to manually copy the files `lib`, `bin`, `include`, & `share` directories from `${SUPERBUILD_INSTALL_PREFIX}` (aka `${CMAKE_BINARY_DIR}/Install`) to `${PREFIX}/foo`). 

Can you generate the analogous build sequence for OSX?

**Comment by rlizzo** [comment]
Also, I forgot to mention that since conda automatically prepends the script directories to the bashrc profile, the utility of the `vmtk_env.sh` file is automatically taken care of. We don't have to do a thing to get the same behavior as before when specifying `source ../vmtk_env.sh`

**Comment by rlizzo** [comment]
@lantiga  Can you please create a new repository in the vmtk organization named "conda-recipes" (I have insufficient permissions). The reasons are twofold:

1) The community has adopted separating the build recipe from the repository code as a best practice. 

2) I am going to build and package VTK as a separate conda package published on the VMTK anaconda channel. By doing this (and setting `USE_SYSTEM_VTK=ON` during VMTK packaging), it will prevent runtime conflicts if a user has both VMTK and VTK installed in the same environment. Since VMTK includes VTK as a builtin module, when anaconda solves the build config for new package installs, it does not know that VTK is already included inside of VMTK, and will install it twice. This could be a big problem down the line since we may get a situation where two different versions of VTK are installed and are not correctly selected. By including VTK as a requirement in the VMTK meta.yaml build file, and linking it to an appropriate version uploaded to the VMTK anaconda channel, conda will be able to solve for version compatibility and prevent conflicts. 

Please let me know if you have any issues with this. I'm also thinking about doing this for ITK as well, but I won't get around to that today.

**Comment by lantiga** [comment]
Hi Rick, great job!
If you need CMake to install in specific locations, you can change the value of the CMAKE_INSTALL_PREFIX variable. See for instance in `SuperBuild.cmake` the definition of `SUPERBUILD_INSTALL_PREFIX` (hard-coded to `${CMAKE_BINARY_DIR}/Install`). That variable is then used as `CMAKE_INSTALL_PREFIX` for the other projects (VTK, ITK and vmtk), which would otherwise be installed in `/usr/local/` by default. By controlling `CMAKE_INSTALL_PREFIX` in CMake you can avoid copying files manually.

I'll create the `conda-recipes` repository.

So we'll be using pinning or something like it? (https://github.com/conda/conda/issues/3721). I mean, when a user already has VTK from another conda package (there's a bunch of them https://anaconda.org/search?q=vtk), will vmtk pick up our pre-built version and make sure they don't interact?

**Comment by lantiga** [comment]
What I meant in the above regarding `SUPERBUILD_INSTALL_PREFIX` should be configurable from the command line, by specifying `-DSUPERBUILD_INSTALL_PREFIX:STRING=your path here`. Let me know if it's not.

**Comment by rlizzo** [comment]
Wow. I way over-complicated that.. That trick with 
`-DSUPERBUILD_INSTALL_PREFIX:STRING=${PREFIX}` fixed the problem flat out! Nice suggestion. 

I'll have to run a few tests to check out how the packages will interact, but at the very least we can try pinning via: 
```
requirements:
  build:
    - vtk =7.1
```
and see how it goes.

**Comment by rlizzo** [comment]
I'm closing this issue as we have moved development to the vmtk/conda-recipes repo.
