### ISSUE TITLE
Installing VMTK via Homebrew Distribution 

### ISSUE THREAD

**Issue by rlizzo** [vmtk/vmtk#177]
@lantiga This issue is created in response to a post on the [vmtk-users](https://groups.google.com/forum/?nomobile=true#!topic/vmtk-users/73AXBsznjRo) forum. 

> Hi,
> I tried to install vmtk following installation on site for binary package on Mac OS 10.12.4 but when I tried the command for install vmtk I have this error. Idea how to solve?
> Python is installed with homebrew (/usr/local/bin/python) and all update, also the code command line tools.
> 
> 
> MacBook-Pro-di-Luca:~ lucagontier$ brew install https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb
> 
> 
> 
> curl: (22) The requested URL returned error: 404 Not Found
> 
> Error: Failure while executing: /usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.0\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.12.4)\ curl/7.51.0 --progress-bar --fail https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb -o /Users/lucagontier/Library/Caches/Homebrew/Formula/vmtk.rb

When we updated cmake to configure the python version at compile time we changed the old `vmtk.rb` file to `vmtk.rb.in `with a cmake copiler flag `${VMTK_PYTHON_VERSION}`

The new file is available at https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb.in but I'm not sure if ammending the install instructions to indicate this link will work as the python version will still not be specified. Luca, Since I have no experience with mac, can you please take a look and advise what the best solution will be for this?

**Comment by rlizzo** [comment]
We also need to update the documentation at http://www.vmtk.org/download/ to reflect these changes. Opening a new issue dedicated to this now. Please see Issue #178

**Comment by lantiga** [comment]
Since we'll probably transition to anaconda, for the time being I just updated the documentation to point to `https://raw.githubusercontent.com/vmtk/vmtk/v1.3.2/distribution/homebrew/vmtk.rb`, which by the way is the correct thing to do, since the brew formula downloads the `v1.3.2` snapshot.
Thank you!

**Comment by lantiga** [comment]
For a future release, I changed vmtk.rb to handle a `--with-python3` option.
