### ISSUE TITLE
Improper string comparison for vmtksurfacesmoothing.py

### ISSUE THREAD

**Issue by normanius** [vmtk/vmtk#183]
**Issue**: In certain circumstances, vmtksurfacesmoothing fails with

> Error: smoothing method not supported.

although the string containing the method is correct: `vmtkSurfaceSmoothing.Method == 'taubin' ` yields `True`.

**Details**: In [vmtksurfacesmoothing.py, around line 63](https://github.com/vmtk/vmtk/blob/master/vmtkScripts/vmtksurfacesmoothing.py#L63), the method string is compared with the wrong string comparison. The issue is described nicely in [this stackoverflow article](https://stackoverflow.com/questions/1504717). Indeed,`vmtkSurfaceSmoothing.Method is 'taubin' ` yields `False` in my case (where the method string is read as a command-line argument using argparse). 

**Solution**: 
Change `if self.Method is '<method>'` to `if self.Method == '<method>'`, with `<method>` being either `'laplace'` or `'taubin'`. This is considered the proper way of comparing strings literally in python.

**Comment by rlizzo** [comment]
Thank you @normanius. I just created pull request #187 to address this issue.
