### ISSUE TITLE
Memory leak in vtkvmtkPolyDataSurfaceRemeshing

### ISSUE THREAD

**Issue by normanius** [vmtk/vmtk#185]
**Version**: VMTK-1.3.1, from master branch 

**Issue**: Running vtkvmtkPolyDataSurfaceRemeshing leaks memory.

**Details**: I figured out that in [vtkvmtkPolyDataSurfaceRemeshing.cxx::L657](https://github.com/vmtk/vmtk/blob/master/vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataSurfaceRemeshing.cxx#L657), in method `vtkvmtkPolyDataSurfaceRemeshing::IsPointOnEntityBoundary()`, a `vtkIdList` object is created without being deleted after usage.

Inserting `ptCells->Delete();` at the end of the function solved the issue for me. Memory leak was solved, the remesher continued to run stably.

**How to reproduce**
```
   def remesh():
      source = vtk.vtkSphereSource()
      source.SetThetaResolution(200)
      source.SetPhiResolution(200)
      source.Update()

      remeshed = vmtkscripts.vmtkSurfaceRemeshing()
      remeshed.Surface = source.GetOutput()
      remeshed.ElementSizeMode = 'area'
      remeshed.TargetArea = 0.05
      remeshed.NumberOfIterations = 5
      remeshed.PreserveBoundaryEdges = False
      remeshed.Execute()

   for i in range(100):
      print "---", i
      remesh()
```

**Comment by rlizzo** [comment]
Thank you @normanius . I have submitted your solution in Pull Request #186 .
