### ISSUE TITLE
VTK 8.0.1 already...

### ISSUE THREAD

**Issue by jiapei100** [vmtk/vmtk#194]
should I tick ***VMTK_USE_VTK7*** or NOT?

Cheers

**Comment by lantiga** [comment]
If you build using SuperBuild and have VMTK_USE_VTK7, vmtk will download and build VTK7.1.0 and link against it.
VTK 8 will come soon - note that we are not using any VTK8-specific feature at the moment.

**Comment by lantiga** [comment]
I just pushed a VMTK_USE_VTK8 flag (ON by default), building against VTK 8.0.1. If OFF, it builds against VTK 7.1.0
