### ISSUE TITLE
netgen could not load the .stl file

### ISSUE THREAD

**Issue by zhaoalex266** [vmtk/vmtk#203]
Hi, guys

Following the guide from:
http://www.vmtk.org/tutorials/NetgenWay.html

The exported .stl geometry could not be read by NGSolve 6.2.

Any specific guide to export .stl format from vmtk？

Thank you!
Alex

**Comment by rlizzo** [comment]
Hey Alex, can you share the commands and data that this failed for? Still export is currently working for me.

**Comment by zhaoalex266** [comment]
Hi rlizzo,

Thank you for your response. I figure it out. The .stl export from vmtk is OK and it can be loaded in most 3D software I have except Netgen. Directly opening the .stl file in NGSolve 6.2 could not work. But NGSolve can open the file after it is re-saved in some other 3D software, like geomagic. I guess there is some encrypt or syntax for the latest NGSolve, which could recognize the most basic .stl format.

Cheers!

**Comment by rlizzo** [comment]
Glad to hear it worked. Thanks for the follow up!
