### ISSUE TITLE
error in tutorials-parent vessel reconstruction

### ISSUE THREAD

**Issue by flee1994** [vmtk/vmtk#206]
Hello, everyone. When I was going on the tutorials of vmtk, I got a problems in Clipping of Voronoi Diagram. I use the command, python clipvoronoidiagram.py /home/flee/Desktop/vmtk-dev/old id1. Finally, it goes wrong and shows the error

USAGE:
      ./clipvoronoidiagram.py inputfilesDirectory caseID

Inputfiles Directory	 /home/flee/Desktop/vmtk-dev/old
case ID			 id1

Clipping Voronoi Diagram
Traceback (most recent call last):
  File "clipvoronoidiagram.py", line 276, in <module>
    maskedVoronoiArray    = MaskVoronoiDiagram(originalVoronoiDiagram,patchCenterlines)
  File "clipvoronoidiagram.py", line 33, in MaskVoronoiDiagram
    MaskWithPatch(i,tangent,center,centerMISR,maskArray,centerlines,voronoi)
  File "clipvoronoidiagram.py", line 71, in MaskWithPatch
    tubeFunction.SetInputData(patch)
AttributeError: 'vtkCommonCorePython.vtkvmtkPolyBallLine' object has no attribute 'SetInputData'

Can anyone give some advice and help. Thanks.

**Comment by rlizzo** [comment]
Hey @flee1994, thanks for the bug report. Can you please provide the following info:

1) Operating System
2) VMTK Version (and how you installed it, aka via binaries, or via anaconda?)
3) Any modifications you made to the script to get it to run? 

Thanks! Will look info this asap.

**Comment by flee1994** [comment]
@rlizzo Hey, thanks for your reply. 
1.My operation system is Linux, the detailed information of which is listed as follows,
   Linux flee 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64   
   x86_64 x86_64 GNU/Linux
2.The version of my vmtk-dev, which is installed using the code,  git clone https://github.com/vmtk/vmtk.git. And all requirements are satisfied.(cmake,git,g++ compiler,python)
I set the environment variables by adding the following lines at the end of .bashrc file
    VMTKHOME=/path-to-vmtk-build/Install
    export PATH=$VMTKHOME/bin:$PATH
    export LD_LIBRARY_PATH=$VMTKHOME/lib:$LD_LIBRARY_PATH
    export PYTHONPATH=$VMTKHOME/lib/python2.7/site-packages:$PYTHONPATH
3.no modification to the script.

**Comment by rlizzo** [comment]
Thanks @flee1994. Can you try making a modification to your local copy of [clipvoronoidiagram.py](https://github.com/vmtk/vmtk/blob/master/vmtkApps/CerebralAneurysms/ParentVesselReconstruction/clipvoronoidiagram.py) at the following lines?

https://github.com/vmtk/vmtk/blob/d24aa9498572c5d90e1376d7a869547cd3fda689/vmtkApps/CerebralAneurysms/ParentVesselReconstruction/clipvoronoidiagram.py#L70-L72

simple change `tubeFunction.SetInputData(patch)` to `tubeFunction.SetInput(patch)`. 

I think that should fix the issue. If it does,  please let me know so we can update it in the master branch (or feel free to submit a PR if you want, I'll merge it immediately). If it doesn't, let me know and i'll get into it tonight.

**Comment by flee1994** [comment]
@rlizzo Thank you so much. The problem is solved with your method. I can go on with this tutorial now.

**Comment by rlizzo** [comment]
Thanks! Let me know if there are any more issues. Will push out a fix to the master branch now.

**Comment by rlizzo** [comment]
Closed. fixed in https://github.com/vmtk/vmtk/pull/210
