### ISSUE TITLE
CMake Error on GTest::GTest link target

### ISSUE THREAD

**Issue by oroppas** [vmtk/vmtk#215]
Hi,

On msys2/mingw64, I've got

```
CMake Error at vtkVmtk/vtkMacroKitPythonWrap.cmake:60 (add_library):
  Target "vtkvmtkITKPythonD" links to target "GTest::GTest" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  vtkVmtk/vmtkFunctions.cmake:67 (vtkMacroKitPythonWrap)
  vtkVmtk/Utilities/vtkvmtkITK/CMakeLists.txt:37 (vmtk_build_library)
```
My environment is

- CMake 3.9.6
- gcc.exe (Rev1, Built by MSYS2 project) 7.2.
- itk 4.13.0
- vtk 8.1.0

**Comment by rlizzo** [comment]
Hi @oroppas. You didn't happen to build ITK with `-DBUILD_TESTING:BOOL=FOO` set to `ON` by chance did you? There isn't any code on the vmtk side that calls into the itk testing library (which utilizes GTest).

**Comment by oroppas** [comment]
Hi @rlizzo,

Yeah, I configured ITK with ``-DBUILD_TESTING:BOOL=OFF``.
I'm a bit confused why ITK configuration affects vmtk configuration.

**Comment by rlizzo** [comment]
And just to be clear, with `-DBUILD_TESTING:BOOL=OFF` you still get the GTest Error? 

What exactly is confusing you about why ITK configuration affects the VMTK configuration? I'm not really sure how to best address such a broad topic.

**Comment by oroppas** [comment]
Correct.

Ah, I think I understand.
Can you point me where in VMTK pulls ITK configuration?
This must be a bug on ITK side.

**Comment by rlizzo** [comment]
Here is where we set the ITK parameters (if using superbuild) https://github.com/vmtk/vmtk/blob/70c66d2e9aa742c3358e95984771e2419f4429a4/SuperBuild.cmake#L57-L94

And here is where set ITK as a dependency https://github.com/vmtk/vmtk/blob/70c66d2e9aa742c3358e95984771e2419f4429a4/SuperBuild.cmake#L209-L211

The build / linking steps are specified in the `vmtk_build_library` function defined in https://github.com/vmtk/vmtk/blob/master/vtkVmtk/vmtkFunctions.cmake . This is called once for each file that needs to be compiled / linked.

**Comment by oroppas** [comment]
Okay. Downgrading my system ITK from 4.13.0 to 4.12.2 fixed the problem.

**Comment by rlizzo** [comment]
I'm unable to recreate this bug. I think this is probably a mingw64 issuea, which we have no plans of supporting at this time. Feel free to reopen if this issue continues in the future.
