### ISSUE TITLE
Unable to disable tetgen

### ISSUE THREAD

**Issue by oroppas** [vmtk/vmtk#216]
Hi,

on msys2/mingw64

```-DVMTK_BUILD_TETGEN:BOOL=OFF```

does not set

```VTK_VMTK_BUILD_TETGEN:BOOL=OFF```

CMake is 3.9.6

**Comment by rlizzo** [comment]
Thanks for the report! I'll check this out and put in a fix tonight!

**Comment by rlizzo** [comment]
Fixed in https://github.com/vmtk/vmtk/pull/217. Closing. Thanks for reporting @oroppas!
