### ISSUE TITLE
Change Default Branch Extractor Argument

### ISSUE THREAD

**Issue by rlizzo** [vmtk/vmtk#228]
Hey @lantiga, 

Just wanted to get your input on whether it would be sensible to change the default `RadiusArrayName` in `vmtkbranchextractor` from null (`''`) to `'MaximumInscribedSphereRadius'`?

https://github.com/vmtk/vmtk/blob/132667ffb015d7ec131f53807e88ee643c4ba966/vmtkScripts/vmtkbranchextractor.py#L24-L37

It seems like a fairly subtle change which would increase usability (I've definitely forgotten to specify `radiusarray` via both command line usage and through external scripting before). And since leaving the null input does not perform the calculations, and does not throw a warning or error,  I could see improper usage being hard to debug if you aren't totally familiar with the library. 

I'm not sure if there was a particular reason that the default was set to nothing? Let me know.

**Comment by lantiga** [comment]
Hey Rick! I’m for it.

The unwritten rule has been that output array names have defaults, while input array names don’t. The rationale was that a) you could pipe them or b) you had to know what you were doing.

However, it’s all well and good but I forget that *all the time*. Plus it’s a pain to break pipes up, because you know you’ll have to specify arrays by hand.

So yes, I’d say let’s provide sensible defaults for radius and for all input array names. In any case, piping will overwrite defaults, so there won’t be any side effects on existing setups.

**Comment by rlizzo** [comment]
Thanks for the feedback! 

Now that I'm thinking about it, I'm wondering if it wouldn't be more sensible to just fill in the default array names for every script while we're at it? Thoughts on this below:

I've never encountered a situation where I needed to change the array names from their defaults; I have to imagine that it would be a fairly unusual thing to do (though correct me if I'm wrong on that).

**Pros**
1.  Breaking up pipes would be massively easier, and fewer init arguments would need to be specified for vmtk based python scripts. 
2.  Filling in a few default names and leaving others blank wound't look (or function) ideally. To users, it would essentially appear that some arguments are filled in at random while some aren't. 
3.  Existing functionality wouldn't be broken by this change, since any manual parameters would just override the defaults anyways

**Cons:**
1.  In a nieve implementation, it would no longer be apparent which values were expected to be piped in from the previous script, and which affect the output of the current script. 
2.  It's a fairly large API change, which would require a lot of the documentation to be updated (not really an issue, but worth pointing out) but  though please correct me if i'm wrong). 
3. We don't have robust tests for the pypes module yet, so if something breaks in the implementation, we'll just start seeing scripts randomly fail with minimal indication that the pypes module is to blame. 

I'm personally thinking that the Pros far out-weigh the cons, but point 1 & 3 would have to be addressed. I'm all for it if you are.

**Comment by lantiga** [comment]
Hi Rick! Yes, sorry that it didn't emerge clearly from my previous comment: I strongly suggest that, if we make this change for this script, we do it for all of them.

In terms of cons, I don't think it's so big of an API change. Only the tutorials would need to be updated, maybe just mentioning that one can also avoid specifying all those array names (we could keep them in the tutorial just for information purposes).

Soo, it's a go!

**Comment by rlizzo** [comment]
Excellent! Let's discuss during our call monday!
