### ISSUE TITLE
vmtk on screen text is extra large

### ISSUE THREAD

**Issue by kayarre** [vmtk/vmtk#246]
I saw in recent commit that changes were made so that the renderer would resize text, but not the text appears much larger than necessary for the interface.

 `vmtk vmtkcenterlines`

![image](https://user-images.githubusercontent.com/9031253/36748526-ef2746d2-1bac-11e8-9a97-5da70e95b84d.png)

**Comment by rlizzo** [comment]
Dammit, I thought I fixed this bug! Thanks for reporting it Kurt!

Unfortunately (or fortunately, I guess), the lowest resolution screen I have access to is my MacBook (2880 x 1800), where a text size set to font=24 looks great. Is it safe to assume this is on a 1080P or 720P screen? 

The code controlling render font size is in [vmtkScripts/vmtkrender.py](https://github.com/vmtk/vmtk/blob/master/vmtkScripts/vmtkrenderer.py). On a High DPI display, the previous text scaling sizes resulted in text being so small that it was nearly unusable if you hadn't memorized what each line read :)

When I tried to set the scale based on the viewport size [as in this diff here](
https://github.com/vmtk/vmtk/commit/a3c952dbfa55a40d9b654cc24870702172eb55e8#diff-cb777decda5373048a832eddc19a711fR309) , it seemed to work, but any time time to text actor changed (aka, the user entered some sort of input) the actor would rescale based on it's current size, and consistently increase the size until it was totally unmanageable. 

Then I thought in [this change](https://github.com/vmtk/vmtk/commit/4977e3740375cc80c13d773b156a509e49831639#diff-cb777decda5373048a832eddc19a711fR298) that it would scale the apparent font size for each system (like how you can set an apparent percentage for font scaling in most operating systems). Apparently that's not the case. 

I think I'll try using the vtkWindow.getScreenSize() function [documented here](https://www.vtk.org/doc/nightly/html/classvtkWindow.html#aba5273b2f34de10650951cc45b06b722) to dynamically set the text size based on how large the screen is. Hopefully this will result in something that works for everyone. 

Sorry about the inconvenience, but I really appreciate the feedback Kurt! We're prepping for the vmtk 1.4 release now, so please let us know about any other bugs/issues you might be running into! Will update here when a fix is in place!

**Comment by rlizzo** [comment]
fixed in https://github.com/vmtk/vmtk/pull/247
