### ISSUE TITLE
vmtkimagewriter not consistent between formats

### ISSUE THREAD

**Issue by kayarre** [vmtk/vmtk#254]
writing the same image from nrrd to vti or nrrd to mha each have different origins.

from vti: Origin="32.695867086 41.89599113 2.6593247071"
from mha: Offset = -32.695867085974825 -41.895991130092369 2.6593247071163644

Things subsequently don't line up in paraview using the mha format, but using the vti format things line up correctly.

example commands:
vmtkimagewriter -ifile DSA_trans_final.nrrd -ofile DSA_trans_final_vmtk.vti
vmtkimagewriter -ifile DSA_trans_final.nrrd -ofile DSA_trans_final_vmtk.mha

**Comment by rlizzo** [comment]
Thanks for pointing this out Kurt; I think I need to play around with it a bit to understand the issue. Could you upload an example data file to this dropbox folder?

https://www.dropbox.com/request/XQBg7fPjBFeFgViQpb0g

Before I dig in, I'm wondering if your issue can be solved with the `ApplyTransform` and `RasToIjkMatrixCoefficients` options in vmtkImageWriter?  (I think this PR may be related? https://github.com/vmtk/vmtk/pull/155)

**Comment by lassoan** [comment]
Nowadays all medical image computing software pretty much standardized on using LPS coordinate system. Even software that use RAS internally (such as 3D Slicer) uses LPS coordinate system in files, and converts to internal coordinate system on import.

What software do you use that would expect data in RAS coordinate system?

**Comment by kayarre** [comment]
@rlizzo  I uploaded and image volume and will experiment with what you suggest, many thanks. 

@lassoan I didn't realize that the internal vs read/write were different. I think the problem is that slicer handles the images properly but it doesn't do the same thing for say a surface mesh. When a surface mesh is imported into slicer there is no conversion to RAS therefore it mush be pre-transformed and when you write the surface after slicer transformation it's written as is (as far as I can tell) it's still in RAS. So I need a way for things to end up in the same space when I export them and view them (Paraview in my case) Thank you for the feedback.

**Comment by kayarre** [comment]
@rlizzo using the ApplyTransform option only works for VTKIO formats (nrrd, mha... etc)
I have implemented a work around by adding vtkXMLStructuredGridWriter in the vmtkimagewriter as the vti format is always axis aligned. Writing to vts format provides a means to have a format that can be viewed in paraview in the correct coordinate system

**Comment by rlizzo** [comment]
This is resolved in #255
