### ISSUE TITLE
JOSS - Please specify the target audience

### ISSUE THREAD

**Issue by wouterpotters** [vmtk/vmtk#284]
Another minor issue that came up while following the JOSS [reviewer guidelines](https://joss.theoj.org/about#reviewer_guidelines). The authors clearly state "what problems the software is designed to solve", but it is not clear "who the target audience is". This would be beneficial for possible future users. Please add this info on either the GitHub website or the vmtk website (or both).

**Comment by rlizzo** [comment]
This has been addressed in https://github.com/vmtk/vmtk/pull/287. 

Thank you for the feedback @wouterpotters. I'll leave it to you to close the issue if this satisfies the requirements.

**Comment by wouterpotters** [comment]
Fixed.
