### ISSUE TITLE
JOSS - Installation instructions 

### ISSUE THREAD

**Issue by wouterpotters** [vmtk/vmtk#286]
For non-anaconda Mac users, please add this line (or something similar) to the installation instructions: "Start the newly installed vmtk anaconda environment using `source activate foo`"

**Comment by wouterpotters** [comment]
also, please include an example where the use of double quotes in pypepad (''/path/to/dicomfiles'' in stead of '/path/to/dicomfiles') is illustrated. This avoids a lot of user confusion for new vmtk users.

**Comment by rlizzo** [comment]
Hi @wouterpotters, I just addressed the install instructions. 

For your second point can you link to the tutorial you're referring to (where  '/path/to/dicomfiles' is illustrated)?

**Comment by wouterpotters** [comment]
I meant this one. I remember several first time users not understanding the fact that two '' are required to encompass a path with spaces (would be good to mention this in the 'getting started' page in order to not deter new users: http://www.vmtk.org/documentation/getting-started.html)

PS: please note that no ' are used on that page right now, but this example only works when a user has no spaces.

**Comment by rlizzo** [comment]
Thanks! Addressed in https://github.com/vmtk/vmtk.github.com/pull/14

**Comment by wouterpotters** [comment]
Fixed

**Comment by wouterpotters** [comment]
Despite the fact that there already is a lot of useful documentation for both users and developers: issue with (incomplete) documentation: https://github.com/vmtk/vmtk/issues/288

Improving this point would improve the open source aspect of vmtk
