### ISSUE TITLE
JOSS - Incomplete documentation

### ISSUE THREAD

**Issue by wouterpotters** [vmtk/vmtk#288]
The documentation for vmtk could be improved:

1. Create an description for every python script (https://www.vmtk.org/documentation/vmtkscripts.html is almost complete)

2. http://www.vmtk.org/doc/html/ for the C++ classes is incomplete. There are very few items that have user friendly help information here (besides the automatically generated content). It should be rather straightforward to add more documentation (i.e. human readable explanations for the classes) to the C code, so that contributors quickly have an idea what the file is supposed to do; doxygen has some features to automate most of this: http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html, although manual typing is still required (once).

**Comment by rlizzo** [comment]
Ahh.. updating the doxygen build and C++ code documentation has been on my to-do list for way to long. Glad to finally have a reason to spend time on it.

@lantiga, let's discuss the best way to do this.

**Comment by rlizzo** [comment]
Hi @wouterpotters, just making you aware I've addressed point 1 of https://github.com/vmtk/vmtk/issues/288#issue-325029959

**Comment by rlizzo** [comment]
Closed per acceptance of JOSS paper
