### ISSUE TITLE
Remove out of date branches in repository

### ISSUE THREAD

**Issue by rlizzo** [vmtk/vmtk#296]
@lantiga, since I'm on a bit of a repository cleanup spree, I noticed that there are a few branches in the vmtk/vmtk repo which are seriously out of date: 

https://github.com/vmtk/vmtk/branches

Notably:
- vtk
- vtk6
- revert-235-developer-setup
- anaconda

The `revert-235-developer-setup` branch has been merged, and can safely be deleted, but the other three haven't. The anaconda stuff we moved into https://github.com/vmtk/conda-recipes, so that's good to go, but I'm not sure about `vtk` or `vtk6`. Is there any reason to keep them around? 

Can you go ahead and delete those as you see fit?

**Comment by rlizzo** [comment]
Just a reminder: don't delete develop-pypes. Thats the staging branch for: https://github.com/vmtk/vmtk/pull/273

**Comment by lantiga** [comment]
All gone :-) Thanks!
