### ISSUE TITLE
VMTK extension not working?

### ISSUE THREAD

**Issue by kantzoul** [vmtk/vmtk#319]
Hi all,

So I am trying to extract the vessels from a Partial brain MRA scan on 3DSlicer, however I am having a hard time understanding how to use it as I am not familiar with VMTK. I am able to generate a centerline and vesselness filtering to generate the vesselness volume but when I go to use the level set segmentation I only get a piece of the vessels. I have attached a screenshot for you to see.

Kind regards

![6d300f9855d5a12f74f96587671a1a7469deb90a](https://user-images.githubusercontent.com/44903362/48950499-56837500-ef09-11e8-801f-c7239b964b11.jpg)

**Comment by lassoan** [comment]
Level set segmentation can only segment one vessel segment (e.g., a single stenosis).

**Comment by lassoan** [comment]
SlicerVMTK extension has been greatly improved in latest Slicer Stable Release (4.11.20200930). If you have any questions, post it tohttps://discourse.slicer.org/c/community/vmtk
