### ISSUE TITLE
vmtkcenterlines.py not fully compatible with Python3.x through Anaconda

### ISSUE THREAD

**Issue by hkjeldsberg** [vmtk/vmtk#320]
Hello,

I've discovered an issue when using the `pointlist` as the seedselector when creating centerlines. 
The vmtk version which is currently distributed on Anaconda contains the following lines in `vmtkcenterlines.py` at lines 128 and 133 respectively::

`for i in range(len(self.SourcePoints)/3):`
`for i in range(len(self.TargetPoints)/3):`

Running this with Python3.x results in a TypeError. 
To reproduce the error, I've installed vmtk through Anaconda (on a MacBook Pro) through the command

`conda create -n foo -c vmtk python=3.6 itk vtk vmtk`

After activating the environment, the error is reproduced as shown below (in a Python console). 

```
>>> import vtk
>>> from vmtk import vmtkscripts

>>> reader = vtk.vtkXMLPolyDataReader()
>>> reader.SetFileName("C0005/surface/model.vtp")
>>> reader.Update()
>>> surface = reader.GetOutput()

>>> centerlines = vmtkscripts.vmtkCenterlines()
>>> centerlines.Surface = surface
>>> centerlines.SeedSelectorName = "pointlist"
>>> centerlines.SourcePoints = [0,0,0]
>>> centerlines.TargetPoints = [1,1,1]
>>> centerlines.Execute()
Cleaning surface.
Triangulating surface.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/foo/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py", line 595, in Execute
    self.SeedSelector.Execute()
  File "/anaconda3/envs/foo/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py", line 128, in Execute
    for i in range(len(self.SourcePoints)/3):
TypeError: 'float' object cannot be interpreted as an integer
```

If it matters, the surface model is an arbitrary model from the Aneurisk database.

**Comment by kayarre** [comment]
> for i in range(len(self.SourcePoints)/3)


can be modified to 

`for i in range(len(self.TargetPoints)//3)`

this change is already in vmtk master.

**Comment by lassoan** [comment]
As described above, issue has been already fixed.
