### ISSUE TITLE
Conda: renderer failing

### ISSUE THREAD

**Issue by rupertnash** [vmtk/vmtk#321]
Hello! The vmtk package on Conda is exhibiting the bug in the vmtkrenderer 
```
File "/opt/conda/lib/python2.7/site-packages/vmtk/vmtkrenderer.py", line 336, in Initialize
   self.TextActor.GetTextProperty().SetFontSize(fontSize)
TypeError: SetFontSize argument 1: integer argument expected, got float
```
which you've fixed in commit f64d433b9a367822fa0ba042a6b1a7944c8e5265

Any chance of doing a new release in the near future?

Thanks very much,
Rupe

**Comment by lassoan** [comment]
As described above, issue has been already fixed. The fix will become widely available if a new release is created (tracked in #359).

**Comment by jiehyunjkim** [comment]
I faced the same issue. 
```
File "/home/username/miniconda3/envs/vmtk/lib/python2.7/site-packages/vmtk/vmtkrenderer.py", line 336, in Initialize
    self.TextActor.GetTextProperty().SetFontSize(fontSize)
TypeError: SetFontSize argument 1: integer argument expected, got float
```
Any idea how to fix it?
