### ISSUE TITLE
If I can choose not to install by anaconda?

### ISSUE THREAD

**Issue by Ranglage** [vmtk/vmtk#325]
I'd like to build a docker image (i would like to share the dockerfile when it is completed) to rapid deployment. So I don't like install this project by anaconda.
So could you provide another install method?

**Comment by lassoan** [comment]
You can build VMTK yourself, its only dependency is VMTK.

**Comment by saskra** [comment]
> I'd like to build a docker image (i would like to share the dockerfile when it is completed)

Did you succeed in doing that? I would be very interested in a docker image of vmtk as installation via conda is not working on every operating system.
