### ISSUE TITLE
how to compile vmtk source code on win10

### ISSUE THREAD

**Issue by junqiangchen** [vmtk/vmtk#327]
hello,
i have installed vmtk in python on win10 successfully.
but i want use vmtk in c++,so i use git clone the whole project,i use cmake and vs2015 to compile it,and have error message.can anyone how to compile it on win10?
thanks

**Comment by junqiangchen** [comment]
错误	LNK1112	妯″潡璁＄畻鏈虹被鍨嬧€淴86鈥濅笌鐩爣璁＄畻鏈虹被鍨嬧€渪64鈥濆啿绐?[D:\Project\3dlib\VMTK\vmtk-Bin\VMTK-Build\CMakeFiles\CMakeTmp\cmTC_ab243.vcxproj]	VMTK	D:\Project\3dlib\VMTK\vmtk-Bin\cmTC_ab243.dir\Debug\testCCompiler.obj	1	

错误	LNK1112	妯″潡璁＄畻鏈虹被鍨嬧€淴86鈥濅笌鐩爣璁＄畻鏈虹被鍨嬧€渪64鈥濆啿绐?[D:\Project\3dlib\VMTK\vmtk-Bin\VTK-Build\CMakeFiles\CMakeTmp\cmTC_4b0f2.vcxproj]	VTK	D:\Project\3dlib\VMTK\vmtk-Bin\cmTC_4b0f2.dir\Debug\testCCompiler.obj	1	

错误	LNK1112	妯″潡璁＄畻鏈虹被鍨嬧€淴86鈥濅笌鐩爣璁＄畻鏈虹被鍨嬧€渪64鈥濆啿绐?[D:\Project\3dlib\VMTK\vmtk-Bin\ITK-Build\CMakeFiles\CMakeTmp\cmTC_25e08.vcxproj]	ITK	D:\Project\3dlib\VMTK\vmtk-Bin\cmTC_25e08.dir\Debug\testCCompiler.obj	1

**Comment by junqiangchen** [comment]
i have successfully compiled the vmtk on win10

**Comment by 447983454** [comment]
could you please give me some information on how you solved the compiling problem?
I might be suffering similar problem as you did

**Comment by lassoan** [comment]
We build VMTK on Windows, Linux, and MacOS as a 3D Slicer extension every day. What is the error that you are getting? What operating system and compiler do you use?

**Comment by yellowfisher** [comment]
> i have successfully compiled the vmtk on win10

你好，我遇到了跟你一样的问题，请问你是怎么解决的？
