### ISSUE TITLE
how to output Voronoi diagram when extracting centerline

### ISSUE THREAD

**Issue by junqiangchen** [vmtk/vmtk#328]
hello,
i have builded the project of extracting centerline with vtkvmtkPolyDataCenterlines class,just like the http://www.vmtk.org/tutorials/Centerlines.html result,but i want output the Voronoi diagram,so i write code like this:
vtkSmartPointer<vtkvmtkPolyDataCenterlines> centerlinesFilter = vtkSmartPointer<vtkvmtkPolyDataCenterlines>::New();
	centerlinesFilter->SetInputData(m_cappedSurface);
	centerlinesFilter->SetSourceSeedIds(m_sourceIds);
	centerlinesFilter->SetTargetSeedIds(m_targetIds);
	centerlinesFilter->SetAppendEndPointsToCenterlines(m_appendEndPointsFlag);
	centerlinesFilter->SetGenerateVoronoiDiagram(m_appendEndPointsFlag);
	centerlinesFilter->SetRadiusArrayName("Radius");
	centerlinesFilter->SetEdgeArrayName("Edge");
	centerlinesFilter->SetEdgePCoordArrayName("PCoord");
	centerlinesFilter->Update();
but this is not output the Voronoi diagram,can anyone tell me how to do it in C++?
thank you

**Comment by NeuZhangQiang** [comment]
You can try:
```
centerlinesFilter->GetVoronoiDiagram();
```

In addition, I have a question. The centerlinesFilter need two input: 
```
centerlinesFilter->SetSourceSeedIds(m_sourceIds);
centerlinesFilter->SetTargetSeedIds(m_targetIds);
```
However, the m_sourceId/m_targetIds are only Ids rather than the actually coordinate. How does the centerlinesFilter get the real coordinate of source/target points?
