### ISSUE TITLE
What is the unit of smoothing passband?

### ISSUE THREAD

**Issue by mirtatae** [vmtk/vmtk#334]
Hi VMTKers,

I am wondering what is the unit of passband parameter in the surface smoothing function (vmtksurfacesmoothing). for example, when we say:

`vmtksurfacesmoothing -ifile model.vtp -passband 0.1 -iterations 30`

What is 0.1?

Thanks,
Amirtaha

**Comment by lassoan** [comment]
Passband and NumberOfIterations are used as inputs for vtkWindowedSincPolyDataFilter. You can find its definition in its documentation: https://vtk.org/doc/nightly/html/classvtkWindowedSincPolyDataFilter.html#a4cff4b6b76e02391caf2d2662a224f59
