### ISSUE TITLE
vmtkimagevesselenhancement does nothing

### ISSUE THREAD

**Issue by saskra** [vmtk/vmtk#336]
I used the following command: 
`vmtkimagereader -f tiff -ifile example.tif --pipe vmtkimagevesselenhancement -sigmamin 2 -sigmamax 6 -sigmasteps 4 -alpha 0.5 -beta 500.0 -gamma 500.0 --pipe [...]` 

It works with the old unsupported Python 2.7 Windows version of VMTK, but it does not work anymore with the new version for Python 3.6 freshly installed via Anaconda. It just states "Executing vmtkimagevesselenhancement ..." but then immediately stops without producing output.

**Comment by lassoan** [comment]
I don't know if it helps at all, but in 3D Slicer's Python 3.6.7 environment, vessel enhancement works well (see complete segmentation example [here](https://lassoan.github.io/SlicerSegmentationRecipes/VesselSegmentationBySubtraction/)):

```python
import vtkvmtkSegmentationPython as vtkvmtkSegmentation
v = vtkvmtkSegmentation.vtkvmtkVesselnessMeasureImageFilter()
v.SetInputData(inImage)
v.SetSigmaMin(minimumDiameterMm)
v.SetSigmaMax(maximumDiameterMm)
v.SetNumberOfSigmaSteps(discretizationSteps)
v.SetAlpha(alpha)
v.SetBeta(beta)
v.SetGamma(contrastMeasure)
v.Update() 
```

**Comment by saskra** [comment]
Thanks, I will have a look. But I would prefer a command line tool.

**Comment by saskra** [comment]
I do not know whether this is THE problem, but it is definitely A problem - it messes with the paths:

```
vmtkimagereader -f tiff -ifile "C:\test\example.tif"

Automatic piping vmtkimagereader
Parsing options vmtkimagereader
    Format = tiff
    InputFileName = C:	est\example.tif
Explicit piping vmtkimagereader
Input vmtkimagereader members:
    Id = 0
    Disabled = 0
    Format = tiff
    GuessFormat = 1
    UseITKIO = 1
    Image = 0
    InputFileName = C:	est\example.tif
    InputFilePrefix = 
    InputFilePattern = 
    DataExtent = [-1, -1, -1, -1, -1, -1]
    HeaderSize = 0
    DataSpacing = [1.0, 1.0, 1.0]
    DataOrigin = [0.0, 0.0, 0.0]
    DesiredOrientation = native
    DataByteOrder = littleendian
    DataScalarType = float
    FileDimensionality = 3
    Flip = [0, 0, 0]
    AutoOrientDICOMImage = 1
    ImageOutputFileName = 
Executing vmtkimagereader ...
ERROR: In ..\vtkVmtk\Utilities\vtkvmtkITK\vtkvmtkITKArchetypeImageSeriesReader.cxx, line 220
vtkvmtkITKArchetypeImageSeriesScalarReader (0000013C3C52CC70): vtkvmtkITKArchetypeImageSeriesReader::ExecuteInformation: Archetype file C:	est/example.tif does not exist.

ERROR: In ..\Common\ExecutionModel\vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0000013C3C5D7390): Algorithm vtkvmtkITKArchetypeImageSeriesScalarReader(0000013C3C52CC70) returned failure for request: vtkInformation (0000013C3E55A260)
  Debug: Off
  Modified Time: 142
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 
```

**Comment by lassoan** [comment]
> Thanks, I will have a look. But I would prefer a command line tool.

You don't need to use the GUI. You can run Python scripts from the command-line, as you would do it in any other Python environment.

    $ PythonSlicer -c 'import vtkvmtkSegmentationPython as vtkvmtkSegmentation; v = vtkvmtkSegmentation.vtkvmtkVesselnessMeasureImageFilter(); ...; v.SetInputData(...); v.SetSigmaMin(...); v.SetSigmaMax(...); v.Update(); ...'

**Comment by Ramtingh** [comment]
Does it help if you cast it to to float first? I assume you're running into this issue #243
`vmtkimagereader -f tiff -ifile example.tif --pipe vmtkimagecast -type float --pipe vmtkimagevesselenhancement -sigmamin 2 -sigmamax 6 -sigmasteps 4 -alpha 0.5 -beta 500.0 -gamma 500.0 --pipe [...]`

**Comment by saskra** [comment]
Yes, that's it, thanks!
