### ISSUE TITLE
CenterlineSections crashed

### ISSUE THREAD

**Issue by junqiangchen** [vmtk/vmtk#338]
hi,
i used vmtkCenterlineSections to extract centerline sections,but the program is crashed.

here is my code:
`from vmtk import vmtkscripts

reader1 = vmtkscripts.vmtkSurfaceReader()
reader1.InputFileName = "D:\Project\python\\vesselproject\\result1\\64vessel.vtk"
reader1.Execute()

reader2 = vmtkscripts.vmtkSurfaceReader()
reader2.InputFileName = "D:\Project\python\\vesselproject\\result1\\64vesselcenterline.vtk"
reader2.Execute()

branchsections = vmtkscripts.vmtkCenterlineSections()
branchsections.Surface = reader1.Surface
branchsections.Centerlines = reader2.Surface
branchsections.Execute()
print("==========>branches centerline sections<=========")
vmtktoNumpy = vmtkscripts.vmtkCenterlinesToNumpy()
vmtktoNumpy.Centerlines = branchsections.CenterlineSections
vmtktoNumpy.Execute()
branchsections_dict = vmtktoNumpy.ArrayDict
surfacewriter = vmtkscripts.vmtkSurfaceWriter()
surfacewriter.Surface = branchsections.CenterlineSections
surfacewriter.Mode = "ascii"
surfacewriter.OutputFileName = "centerlinesection.vtk"
surfacewriter.Execute()`

**Comment by junqiangchen** [comment]
this is input model and centerline model:![中心线](https://user-images.githubusercontent.com/28638716/64932887-7effa580-d874-11e9-9bb8-fe96823ea29f.PNG)
the program crash error:![错误截图](https://user-images.githubusercontent.com/28638716/64932888-8161ff80-d874-11e9-9f7a-c83990cf50ca.PNG)

**Comment by lassoan** [comment]
You can try to clean and simplify the input mesh. If you still encounter issues, then upload the mesh file somewhere and post the link here.

**Comment by junqiangchen** [comment]
> You can try to clean and simplify the input mesh. If you still encounter issues, then upload the mesh file somewhere and post the link here.

i try smooth the input mesh,and can get centerlinesections
