### ISSUE TITLE
How to extract all the center lines at one time rather than pick start/end point?

### ISSUE THREAD

**Issue by qiang-zhang-neu** [vmtk/vmtk#343]
VMTK is a very good project. It can extract the center line by giving the start and end point. However, I want to extract all the center lines at one time. Is there any function can finish it? Could you please give me a demo? Any suggestion is appreciated.

**Comment by lassoan** [comment]
You can extract centerline of a complete tree but you need to segment the image first and create a surface mesh from the segmented tree.
