### ISSUE TITLE
Incorrect wall shear rate calculation

### ISSUE THREAD

**Issue by myousefi2016** [vmtk/vmtk#345]
https://github.com/vmtk/vmtk/blob/64675f598e31bc6be3d4fba903fb59bf1394f492/vtkVmtk/Misc/vtkvmtkMeshWallShearRate.cxx#L161

Based on above formula in this line, it seems you just took the normal component of velocity gradient tensor as wall shear rate, which is obviously incorrect. The correct equation for wall shear rate is:

<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{S}&space;=&space;\frac{1}{2}(\nabla&space;\mathbf{u}&space;&plus;&space;(\nabla&space;\mathbf{u})^{T})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{S}&space;=&space;\frac{1}{2}(\nabla&space;\mathbf{u}&space;&plus;&space;(\nabla&space;\mathbf{u})^{T})" title="\mathbf{S} = \frac{1}{2}(\nabla \mathbf{u} + (\nabla \mathbf{u})^{T})" /></a>

<a href="https://www.codecogs.com/eqnedit.php?latex=\vec{\tau}&space;=&space;2(\mathbf{S}\cdot\mathbf{n}&space;-&space;(\mathbf{n}\cdot&space;\mathbf{S}&space;\cdot&space;\mathbf{n})\mathbf{n})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\vec{\tau}&space;=&space;2(\mathbf{S}\cdot\mathbf{n}&space;-&space;(\mathbf{n}\cdot&space;\mathbf{S}&space;\cdot&space;\mathbf{n})\mathbf{n})" title="\vec{\tau} = 2(\mathbf{S}\cdot\mathbf{n} - (\mathbf{n}\cdot \mathbf{S} \cdot \mathbf{n})\mathbf{n})" /></a>

Any plan to fix it?

**Comment by lassoan** [comment]
I don't think there is any plan to change this (probably nobody has been aware that this could be wrong), but if you submit a pull request with a fix and an explanation (link to the relevant formula) then probably it'll be merged.

**Comment by myousefi2016** [comment]
@lassoan See #347

**Comment by lassoan** [comment]
Thank you. It'll be a good test if VMTK maintainers can still allocate some time to review and merge changes.

**Comment by uschille** [comment]
The vmtk script computes wall shear rate as a vector defined as the contraction of velocity gradient with the surface normal. This definition is presumably based on
![](http://www.sciweavers.org/tex2img.php?eq=%5Cfrac%7B%5Cpartial%20%28%5Cvec%7Bu%7D%5Ccdot%5Chat%7Bt%7D%29%7D%7B%5Cpartial%20%5Chat%7Bn%7D%7D%20%3D%20%28%5Chat%7Bn%7D%5Ccdot%5Cnabla%5Cotimes%5Cvec%7Bu%7D%29%5Ccdot%5Chat%7Bt%7D.&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)
The definition used by the vmtk script is discussed in this thread https://sourceforge.net/p/vmtk/mailman/message/31010344/.

**Comment by lantiga** [comment]
@myousefi2016 thank you for submitting the issue and the PR.
This is very relevant issue. I'm going to check the code and merge as soon as possible.

We have an issue on CI but I unfortunately have little bandwidth to fix it right now. We should do that and update the packages.

**Comment by lantiga** [comment]
Thank you @uschille. I am also wondering about changing the semantics. On the other end, the current results may lead to unexpected results if you come from a full tensor perspective.

My preferred approach would be for the two implementations to coexist, so that one can choose one or the other (and expose that at the `vmtkmeshshearrate` script level. Seeing the option will make things less confusing and immediately apparent.

As for the code, a UoT student sent me a cleaner implementation tonight along with a nice report, which triggered me to look at this issue. I encouraged him to participate to the discussion.

**Comment by uschille** [comment]
> My preferred approach would be for the two implementations to coexist, so that one can choose one or the other (and expose that at the vmtkmeshshearrate script level. Seeing the option will make things less confusing and immediately apparent.

That is a sensible option. The difference should be negligible for laminar flow.

**Comment by lantiga** [comment]
I've sent in a new PR #348 based on all the inputs I had. An extra look would be appreciated, thanks.
