### ISSUE TITLE
build fails: override for vtkvmtkPolyBallLine does not override

### ISSUE THREAD

**Issue by RizzerOnGitHub** [vmtk/vmtk#346]
Trying to build vmtk 1.4.0 for Debian unstable,
  vmtk   1.4.0
  VTK 7.1.1
  g++  9.2.1
  cmake  3.16.3

The build gives this error:

    [  7%] Building CXX object vtkVmtk/IO/CMakeFiles/vtkvmtkIOPythonD.dir/vtkvmtkXdaWriterPython.cxx.o
    cd /build/vmtk/obj-x86_64-linux-gnu/vtkVmtk/IO && /usr/bin/c++  -DITK_IO_FACTORY_REGISTER_MANAGER -DvtkvmtkIOPythonD_EXPORTS -I/usr/include/vtk-7.1 -I/build/vmtk/obj-x86_64-linux-gnu/ITKFactoryRegistration -I/usr/include/hdf5/serial -I/usr/include/nifti -I/usr/include/gdcm-3.0 -I/usr/include/double-conversion -I/usr/include/ITK-4.13 -I/build/vmtk/vtkVmtk -I/build/vmtk/vtkVmtk/Common -I/build/vmtk/vtkVmtk/ComputationalGeometry -I/build/vmtk/vtkVmtk/DifferentialGeometry -I/build/vmtk/vtkVmtk/IO -I/build/vmtk/vtkVmtk/Misc -I/build/vmtk/vtkVmtk/Segmentation -I/build/vmtk/vtkVmtk/Contrib -I/build/vmtk/vtkVmtk/Utilities/vtkvmtkITK -I/build/vmtk/obj-x86_64-linux-gnu/vtkVmtk -I/usr/include/python3.7m -I/usr/include/python2.7  -g -O2 -fdebug-prefix-map=/build/vmtk=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/vtkvmtkIOPythonD.dir/vtkvmtkXdaWriterPython.cxx.o -c /build/vmtk/obj-x86_64-linux-gnu/vtkVmtk/IO/vtkvmtkXdaWriterPython.cxx
    In file included from /build/vmtk/vtkVmtk/ComputationalGeometry/vtkvmtkCenterlineBranchExtractor.cxx:24:
    /build/vmtk/vtkVmtk/ComputationalGeometry/vtkvmtkPolyBallLine.h:45:10: error: ‘double vtkvmtkPolyBallLine::EvaluateFunction(double, double, double)’ marked ‘override’, but does not override
       45 |   double EvaluateFunction(double x, double y, double z) VTK_OVERRIDE
          |          ^~~~~~~~~~~~~~~~
    make[3]: *** [vtkVmtk/ComputationalGeometry/CMakeFiles/vtkvmtkComputationalGeometry.dir/build.make:131: vtkVmtk/ComputationalGeometry/CMakeFiles/vtkvmtkComputationalGeometry.dir/vtkvmtkCenterlineBranchExtractor.cxx.o] Error 1
    make[3]: Leaving directory '/build/vmtk/obj-x86_64-linux-gnu'
    make[2]: *** [CMakeFiles/Makefile2:710: vtkVmtk/ComputationalGeometry/CMakeFiles/vtkvmtkComputationalGeometry.dir/all] Error 2

**Comment by lassoan** [comment]
VTK7 is very old. You need to look up an older VMTK version in the revision history that is still compatible with VTK7.
