### ISSUE TITLE
Vmtk Library Not installing. 

### ISSUE THREAD

**Issue by farzad444** [vmtk/vmtk#350]
Hello All, I'm having an issue installing the VMTK library on my python
I am using Spyder 4 with Python base 3.7.6 and when I put in the command [pip install vmtk], I get the following error:
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement vmtk (from versions: none)
ERROR: No matching distribution found for vmtk

is there a fix for this? thank you in advance

**Comment by lassoan** [comment]
VMTK is is only available for Python2 on PyPI (https://pypi.org/project/vmtk/#history). Some Python3 versions are available on conda (https://anaconda.org/vmtk/vmtk/files).

Task of creating a new VMTK release is tracked in this issue: #359
