### ISSUE TITLE
No module named 'vtkRenderingOpenGL2Python'

### ISSUE THREAD

**Issue by philippa1812** [vmtk/vmtk#351]
Hi,
I installed vmtk via "conda create -n foo -c vmtk python=3.6 itk vtk vmtk" without any problems. However, when I try to run a vmtk script I get the following error:

No module named 'vtkRenderingOpenGL2Python'
Traceback (most recent call last):
  File "~/.conda/envs/vmtk/lib/python3.6/site-packages/vtk/vtkRenderingOpenGL2.py", line 5, in <module>
    from .vtkRenderingOpenGL2Python import *
ImportError: libLLVM-3.3.so: cannot open shared object file: No such file or directory

Any help would be appreciated!

**Comment by lassoan** [comment]
VMTK should be made available in PyPI and conda, but until it works well, you can always use VMTK in 3D Slicer's Python environment. Just install 3D Slicer and its [SlicerVMTK extension](https://github.com/vmtk/SlicerExtension-VMTK). It also gives nice and convenient GUI to specify inputs and visualize results.

**Comment by stefanonardo** [comment]
Hi @lassoan,
I tried to run [this script](https://github.com/vmtk/vmtk/blob/master/vmtkScripts/vmtksurfacewriter.py) in the Slicer's python interpreter but it raises many errors. For instance, it throws an ImportError when importing vmtk and, if I try to import directly pypes, pypes module has no attributes/methods.

**Comment by lassoan** [comment]
> Is vmtk still maintaned?

There are various environments maintained by different people with different availability and priority.

I can only comment on the status of VMTK in 3D Slicer's Python environment: we actively maintain it there and upgrade to VTK9's completely reworked build system in the very near future. After that we may have a look at the state of PyPI and conda packages.

> I tried to run this script in the Slicer's python interpreter but it raises many errors

The "PypeS" script that you linked above is a command-line application and not a Python script that you would run directly in an interpreter. Since many features of PypeS scripts are already built into Slicer (all visualizations, input/output data management, etc.), you can usually greatly simplify things and just use these scripts as examples (especially what is in `Execute` method).

**Comment by lassoan** [comment]
Task of creating a new VMTK release is tracked in this issue: #359
Until it is completed, users may build VMTK on their own or use it in Python environment of latest Slicer Stable Release (4.11.20200930).

**Comment by bi3ri** [comment]
@philippa1812 
Same issue here! Solved it by installing llvm directly in the virtual environment.

`create -n vmtk -c vmtk python=3.6 itk vtk vmtk llvm=3.3`

Or in an existing environment:

`conda install llvm=3.3`

**Comment by philippa1812** [comment]
> @philippa1812
> Same issue here! Solved it by installing llvm directly in the virtual environment.
> 
> `create -n vmtk -c vmtk python=3.6 itk vtk vmtk llvm=3.3`
> 
> Or in an existing environment:
> 
> `conda install llvm=3.3`

Thanks, unfortunately this does not work for me. I get "PackagesNotFoundError: The following packages are not available from current channels".

**Comment by 13001231828** [comment]
> > @philippa1812
> > Same issue here! Solved it by installing llvm directly in the virtual environment.
> > `create -n vmtk -c vmtk python=3.6 itk vtk vmtk llvm=3.3`
> > Or in an existing environment:
> > `conda install llvm=3.3`
> 
> Thanks, unfortunately this does not work for me. I get "PackagesNotFoundError: The following packages are not available from current channels".

same question. The VMTK experience on Python is terrible. if you got solution about vmtk, please tell me. thx

**Comment by lassoan** [comment]
I understand your frustration. Everybody would just love to use VMTK in Python, but the reality is that it requires very hard work of people with unique skillset (deep knowledge of VMTK, VTK, CMake, Python packaging on Windows, Linux, and macOS, for PyPI and conda) to take care of this. We have secured funding for this, but even then, it is hard to find the right people and make sure they have time to work on this.

After years of stagnation, we recently updated VMTK to the new VTK9 build system (entirely different from VTK8 and every other CMake build systems out there). It works now on Windows and Linux, but there are macOS packaging errors that are still being sorted out. Then we'll work on PyPI, and it seems that with [volunteers helping out with conda packages](https://github.com/vmtk/vmtk/pull/378) conda packaging will be addressed, too.

**Comment by dhruvshah01** [comment]
> @13001231828 @philippa1812 llvm 3.3 is only available in the "free" conda channel, which is disabled in modern versions of anaconda because those packages are old, have inconsistent metadata and generally [a lot of issues](https://www.anaconda.com/blog/why-we-removed-the-free-channel-in-conda-4-7)
> 
> If you want to install it anyway until new releases get sorted out you have to re-enable the channel: ` conda config --set restore_free_channel true`

This is a really great hack. Works for me! Process goes something like,

1) Go to the particular env - `conda activate vmtk`
2) `conda config --env --set restore_free_channel true` 
3) `conda install llvm=3.3`
