### ISSUE TITLE
Is there any tutorial for python/c++ script?

### ISSUE THREAD

**Issue by NeuZhangQiang** [vmtk/vmtk#352]
vmtk is really a very good project. Currently, I want to use vmtk in python and c++. However, I don't know how to start it. 

For example. vmtk provide a very good [tool](http://www.vmtk.org/tutorials/Centerlines.html) to extract center line. 
The script is:
```
vmtkcenterlines -ifile foo.vtp -ofile foo_centerlines.vtp
```

I want to know the pipelines for vmtkcenterlines, and the functions are called by vmtkcenterlines, thus, I can implement the python/c++ code in my own project. Is there any tutorial for python/c++ script?

**Comment by lassoan** [comment]
Lots of information is available to get you started:
- get high-level understanding of the algorithms from Luca's thesis (http://lantiga.github.io/media/AntigaPhDThesis.pdf)
- detailed description of the algorithms are in the source code
- examples and documentation for using the C++ classes are available in the pypes scripts (https://github.com/vmtk/vmtk/tree/master/vmtkScripts)
- tutorials are available on the VMTK website (http://www.vmtk.org/tutorials/)
- to build interactive applications using VMTK in C++ or Python, you can use 3D Slicer and SlicerVMTK extension (https://github.com/vmtk/SlicerExtension-VMTK#the-vmtk-extension-for-3d-slicer)

**Comment by NeuZhangQiang** [comment]
@lassoan Thank you very much for your reply. These tutorials help me a lot. 
In addition, if there are some examples for using vmtk in c++? Just like some vtk/itk examples including cpp and cmakelist?
