### ISSUE TITLE
How to extract center lines from small vessel?

### ISSUE THREAD

**Issue by NeuZhangQiang** [vmtk/vmtk#354]
VMTK is really a good tool. I am using VMTK to extract center lines from vessel. And I have two questions:

1. Currently, it would cost 8s for one calculation. Is there any method to accelerate it? Can we use gpu in VMTK?

2. I find it failed for VMTK to extract center line from small vessel. Just like the following picture:

![image](https://user-images.githubusercontent.com/62534955/91787120-b315d700-ec3b-11ea-8c31-1f6fa801e2c1.png)

VMTK can not extract center line for the two points (source and target point). Is there any method to extract center line for small vessel?

Thanks for any suggestion!

**Comment by lassoan** [comment]
> Currently, it would cost 8s for one calculation. Is there any method to accelerate it? Can we use gpu in VMTK?

You can cut off irrelevant parts of the mesh or decimate your model, but 8s computation time is already good. It is hard to parallelize these algorithms on the GPU, especially if you want to preserve good compatibility with various hardware configurations, but if performance is so critical for you then you can give it a try.

> I find it failed for VMTK to extract center line from small vessel. Just like the following picture

This is not that surprising as the mesh is very low quality, almost discontinuous. You need to more than just a few connecting mesh elements. I would recommend to oversample the input image before segmentation and lower the segmentation threshold to improve connectivity.

**Comment by NeuZhangQiang** [comment]
Thank you very much for your reply. I have another question:

For example, I need to extract the center lines from airway, and the airway looks like:

![image](https://user-images.githubusercontent.com/62534955/91800868-62fb3c80-ec5c-11ea-8103-be812f6c6bfa.png)

If the source point is 0, and target point is 1, the output is OK:

![image](https://user-images.githubusercontent.com/62534955/91801003-abb2f580-ec5c-11ea-8314-3611e15b5871.png)

If the source point is [1, 1], and target point is [2, 3], the output is also OK:

![image](https://user-images.githubusercontent.com/62534955/91802950-6e029c80-ec5d-11ea-9c88-f1238e36218d.png)

However, if I want to extract the three center lines, and set the source point as [0, 1, 1], target point is [1, 2, 3], the output is:

![image](https://user-images.githubusercontent.com/62534955/91802950-6e029c80-ec5d-11ea-9c88-f1238e36218d.png)

The line [0, 1] is missed. What is the reason to cause this problem?

Moreover, if I want to extract line (0, 1) firstly, and then extract (1,2)/(1,3), the computation time would be double of 8s. How can I save the computation time for this situation?

**Comment by NeuZhangQiang** [comment]
I have one more question: the [tutorial](http://www.vmtk.org/tutorials/Centerlines.html) said that the vtkvmtkPolyDataCenterlines can provide the radius of every point. How can I obtain the radius?
I can obtain the points of center lines as following:
```
        Centerlines = centerlineFilter.GetOutput()
        centerLinePoints = Centerlines.GetPoints()
        voronoiDiagram = centerlineFilter.GetVoronoiDiagram()

        lines = Centerlines.GetLines()
        numberOfLines = lines.GetNumberOfCells()

        points = Centerlines.GetPoints()
        lines.InitTraversal()
        idList = vtk.vtkIdList()

        while lines.GetNextCell(idList):
            n = idList.GetNumberOfIds()

            for id in range(n):

                pointId = idList.GetId(id)
                point = points.GetPoint(pointId)

```
Even I can obtain the voronoi diagram ```voronoiDiagram = centerlineFilter.GetVoronoiDiagram()```, I don't know how to obtain the radius. 

In addition, I want to obtain a mask which is constructed by a list of circles. These circles is centered at the points of extracted center lines, and the radius is the obtained radius. In summary, the mask is a standard tube with the center line and radius obtained from the vtkvmtkPolyDataCenterlines. How can I obtain this mask?

**Comment by lassoan** [comment]
Please post unrelated new questions as separate issues (or to the mailling list).

**Comment by NeuZhangQiang** [comment]
@lassoan I apologize for this unrelated question. And I have post a new issues.
