### ISSUE TITLE
Problem about multiple source/target points for vtkvmtkPolyDataCenterlines

### ISSUE THREAD

**Issue by NeuZhangQiang** [vmtk/vmtk#355]
Dear vmtk developer:

I am using vmtk to extract center lines from airway, and I need some help. For example, the airway looks like:

![image](https://user-images.githubusercontent.com/62534955/91920698-6a722280-ecfc-11ea-90ff-c0fb8aeb5981.png)

If the source point is 0, and target point is 1, the output is OK:

![image](https://user-images.githubusercontent.com/62534955/91920788-9097c280-ecfc-11ea-9ee2-cb68c7ce2541.png)
Fig. 1

If the source point is [1, 1], and target point is [2, 3], the output is also acceptable:

![image](https://user-images.githubusercontent.com/62534955/91920824-a3aa9280-ecfc-11ea-8cf3-291afcb7418b.png)
Fig. 2

However, if I want to extract the three center lines, and set the source point as [0, 1, 1], target point is [1, 2, 3], the output is:

![image](https://user-images.githubusercontent.com/62534955/91920824-a3aa9280-ecfc-11ea-8cf3-291afcb7418b.png)
Fig. 3

The line [0, 1] is missed. What is the reason to cause this problem?

Moreover, if I separately extract line (0, 1) and (1,2)/(1,3), the computation time would be double. How can I reduce the computation time for this situation?

**Comment by lassoan** [comment]
Each `source` points designates a tree root. To extract a single tree, you must set a single `source` point, for example for your case, set `sources` = [0], `targets` = [2, 3]. If you have multiple disconnected trees then place one `source` in each.

In 3D Slicer's VMTK extension, you can get all the endpoints by clicking *Auto-detect* button. To designate a point as `source`, right-click on it and choose `Toggle select point` (selected control points are `targets`, unselected control points are `sources`; all auto-detected control points are set to `target` by default).

**Comment by NeuZhangQiang** [comment]
The reason why I want to separately extract line (0, 1) and line (1,2), (1,3) is: sometimes, it would fail to directly extract the center line from root to the endpoints, because the distal airway is too small. In this situation, we can not obtain any center line. Thus, I want to separately extract line (0, 1), (1, 2) until the endpoints. Even the last segment of airway may be missed, we can obtain most of the center lines.

Is there any method to obtain the tree segment by segment with short computation time?

**Comment by lassoan** [comment]
You need to increase the resolution of the input image, reduce decimation, reduce segmentation threshold to ensure that the path search succeeds. Cut off irrelevant parts of the mesh to increase computation time.

**Comment by NeuZhangQiang** [comment]
@lassoan Thanks for your suggestion, and I would try it. 
I still have a question for line (1, 2), (1, 3) extraction. Since both line (1, 2), (1, 3) start from point 1, why the extract lines are not joined?

![image](https://user-images.githubusercontent.com/62534955/92361338-d26fa100-f120-11ea-8130-768973ab798d.png)

**Comment by lassoan** [comment]
Discussion of this question was moved to https://discourse.slicer.org/t/how-to-obtain-the-complete-center-lines-using-vmtk/14068
