### ISSUE TITLE
How to output the radius from vtkvmtkPolyDataCenterlines 

### ISSUE THREAD

**Issue by NeuZhangQiang** [vmtk/vmtk#356]
The VMTK [tutorial](http://www.vmtk.org/tutorials/Centerlines.html) said that the vtkvmtkPolyDataCenterlines can provide the radius of every point. How can I obtain the radius?
I can obtain the points of center lines as following:

        Centerlines = centerlineFilter.GetOutput()
        centerLinePoints = Centerlines.GetPoints()
        voronoiDiagram = centerlineFilter.GetVoronoiDiagram()

        lines = Centerlines.GetLines()
        numberOfLines = lines.GetNumberOfCells()

        points = Centerlines.GetPoints()
        lines.InitTraversal()
        idList = vtk.vtkIdList()

        while lines.GetNextCell(idList):
            n = idList.GetNumberOfIds()

            for id in range(n):

                pointId = idList.GetId(id)
                point = points.GetPoint(pointId)

Even I can obtain the voronoi diagram voronoiDiagram = centerlineFilter.GetVoronoiDiagram(), I don't know how to obtain the radius.

**Comment by lassoan** [comment]
You can get radius from the centerline extraction filter as point data array in the output polydata. You can set the array name using SetRadiusArrayName before executing the filter.

**Comment by NeuZhangQiang** [comment]
If I know the radius array name: ```centerlineFilter.SetRadiusArrayName('MaximumInscribedSphereRadius')```.

How can I obtain the radius? Could you please provide an example? Python or C++ is OK.

**Comment by lassoan** [comment]
You can get point data as a numpy array as it is done in this convenience method:

https://github.com/Slicer/Slicer/blob/1ce740cc25e6f22f7a2816767656fd414a5973c7/Base/Python/slicer/util.py#L1262-L1274

**Comment by NeuZhangQiang** [comment]
I can get the point as:
```
voronoiDiagram = centerlineFilter.GetVoronoiDiagram()
import vtk
narray = vtk.util.numpy_support.vtk_to_numpy(voronoiDiagram.GetPoints().GetData())
```
However, the shape of narray is: n*3, and I believe this array is the coordinate of center lines. I still can not obtain the radius.

**Comment by lassoan** [comment]
You are right, to get point data arrays (not the point coordinates), you need to use a slightly different method: `arrayFromModelPointData`

https://github.com/Slicer/Slicer/blob/1ce740cc25e6f22f7a2816767656fd414a5973c7/Base/Python/slicer/util.py#L1283-L1293

**Comment by NeuZhangQiang** [comment]
@lassoan Thank you for your nice reply. Finally, I can obtain the radius. 

```
import vtk
voronoiDiagram = centerlineFilter.GetVoronoiDiagram()
centerlinePoints = vtk.util.numpy_support.vtk_to_numpy(voronoiDiagram.GetPoints().GetData())
radius = vtk.util.numpy_support.vtk_to_numpy(voronoiDiagram.GetPointData().GetArray('MaximumInscribedSphereRadius'))
```

Hope it may help others.
