### ISSUE TITLE
limitation of vmtkimagereader with tiff stacks larger than 4 GB

### ISSUE THREAD

**Issue by philippa1812** [vmtk/vmtk#357]
Hi, I am trying to read a tiff image stack which is larger than 4 GB with vmtkimagereader in order to use it for further processing with other vmtk scripts. I noticed that the vmtkimagereader seems to only read in the first slice of the full image stack whenever the tiff stack exceeds 4 GB. Is this a known limitation or am I missing something to make it work? Thanks in advance for any help!

**Comment by lassoan** [comment]
Very few software packages support bigtiff (tiff file >4GB). I think VTK does not support it either and most likely will not support it, as there are many other formats that are more appropriate for 3D image data storage that does not have this limitation and already supported by VTK (for example, NRRD). If you already have your data stored in TIFF then you may look for a software package that can read the TIFF stack and save to NRRD.
