### ISSUE TITLE
How to obtain the complete center lines using VMTK?

### ISSUE THREAD

**Issue by KaryLiang** [vmtk/vmtk#358]
Hello,

I’m trying to obtain center lines from airway using VMTK. After dilating the pixels of airway, i got most of the center line, including from the small airway, looks like this:

![_20201016103816](https://user-images.githubusercontent.com/54094299/96206842-5d537f00-0f9c-11eb-862c-b77bb08338d2.png)

my problem is, why the center lines are broken in the middle? and what would be the best way to get a complete center lines?

![_20201016103824](https://user-images.githubusercontent.com/54094299/96206848-62b0c980-0f9c-11eb-9c88-853c34b02fe8.png)

A similar problem seems to be happened here, the extract lines are not joined:
(https://github.com/vmtk/vmtk/issues/355)

Please help or try to give some ideas how to achieve this. Thanks in advance.

**Comment by lassoan** [comment]
Discussion of this question was moved to https://discourse.slicer.org/t/how-to-obtain-the-complete-center-lines-using-vmtk/14068
