### ISSUE TITLE
Question about multi target seeds

### ISSUE THREAD

**Issue by Puzzled-Hui** [vmtk/vmtk#361]
Hi, i am interesting in your work and buy the VMTKLAB,  but i find when i set the target seeds > 2, the program will be stuck in the procedure of 'Compute Centerlines', when target seeds <= 2, the program functions well, could you tell me whether the software can handle multiple target seeds( > 2) or not? 
Looking forward to your reply.

**Comment by lassoan** [comment]
VMTK library works with multiple seeds (you can give it a try in 3D Slicer, using SlicerVMTK extension, Extract centerline module). I don't know if there is any limitation in VMTKLAB that would prevent you from using multiple target seeds.

**Comment by Puzzled-Hui** [comment]
I am confused about that,  i import a mesh (stl) and chose one source seed and 8 target seeds, then the software

**Comment by lassoan** [comment]
If you share the Slicer scene that you are having problem with then we can have a look. Save the scene as .mrb, upload it to somewhere (dropbox, onedrive, google drive, ...) and post the link here.

**Comment by lassoan** [comment]
Closing the issue due to no response from the reporter.
