### ISSUE TITLE
Point list vmtkcenterlines error

### ISSUE THREAD

**Issue by matthewgunther** [vmtk/vmtk#362]
Hello when you feed source/target points into vmtkcenterlines you get this error:

`File "/Users/name/miniconda3/envs/fdo/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py", line 128, in Execute
    for i in range(len(self.SourcePoints)/3):
TypeError: 'float' object cannot be interpreted as an integer`

Which can be fixed by wrapping len with int (line 128 and 133 in vmtkcenterlines.py):

`        for i in range(int(len(self.SourcePoints)/3)):
            point = [self.SourcePoints[3*i+0],self.SourcePoints[3*i+1],self.SourcePoints[3*i+2]]
            id = pointLocator.FindClosestPoint(point)
            self._SourceSeedIds.InsertNextId(id)`

`        for i in range(int(len(self.TargetPoints)/3)):
            point = [self.TargetPoints[3*i+0],self.TargetPoints[3*i+1],self.TargetPoints[3*i+2]]
            id = pointLocator.FindClosestPoint(point)
            self._TargetSeedIds.InsertNextId(id)`

Thank you, this is a wonderful tool by the way :)

**Comment by lassoan** [comment]
Thans for reporting this. I've submitted a pull request with the proposed change (using // operator instead of an extra int() casting, and fixing all other occurrences).
