### ISSUE TITLE
centerline have strange result?

### ISSUE THREAD

**Issue by junqiangchen** [vmtk/vmtk#364]
hi, i use  vmtkscripts.vmtkCenterlines() class with default params in python to calculate centerline,i have tried 30 examples,only part results are very strange,obviously incorrect,i have check the mesh result that is right, can you tell me what is bug in here? i attach the centerline and mesh picture,and two red circle is start point and end point.
thank you 
![捕获](https://user-images.githubusercontent.com/28638716/112587902-6c870480-8e39-11eb-92b1-21597364b6f5.PNG)

**Comment by lassoan** [comment]
The mesh looks noise (especially near the top starting point), but could be OK. No centerline is visible, so it is hard to tell if something wrong or not. If you need further help with this then please post to the [VMTK forum](https://discourse.slicer.org/c/community/vmtk) and include a download link to the data set.
