### ISSUE TITLE
centerlinesection can't calculate error

### ISSUE THREAD

**Issue by junqiangchen** [vmtk/vmtk#366]
hi, i have extracted centerline successfully,but when i calculate centerlinesections,the program is crashed,and i find the vessel mask is like this,some region have three regions separately.
![中心线有缝隙](https://user-images.githubusercontent.com/28638716/113096746-5d80c780-9228-11eb-8dd7-bf32bd76dc68.PNG)
so i guess that centerlinesections not supported two or more regions for calculating section.

**Comment by lassoan** [comment]
Could you post a link to your data set to see if we can reproduce the problem?
