### ISSUE TITLE
Cannot obtain the center line.

### ISSUE THREAD

**Issue by zhang-qiang-github** [vmtk/vmtk#367]
I have two arteries, like:

![image](https://user-images.githubusercontent.com/29271051/121808984-94924100-cc8d-11eb-8738-6c624480890d.png)

I can obtain the centerline for one artery, but fail for the other one. It failed to obtain the centerline between the two red point. 

The running code is:

```
vmtksurfacereader -ifile E:\\DeepCenterLine\\vessel_smooth30.vtp --pipe vmtkcenterlines --pipe vmtkrenderer --pipe vmtksurfaceviewer -opacity 0.25 --pipe vmtksurfaceviewer -i @vmtkcenterlines.o -array MaximumInscribedSphereRadius
```
I have updated the `vessel_smooth30.vtp` to [github](https://github.com/zhang-qiang-github/vmtkdata).

Actually, I run it using python code, and a warning is reported:

```
vtkvmtkSteepestDescentLineTracer: can't find a steepest descent edget. Target not reached.
```
The source point is: [44, 398, 151], and the target point is: [47, 403, 558]

**Comment by lassoan** [comment]
We use issues to keep track of problems and enhancement requests. Please post questions about how to use the toolkit to the VMTK forum: https://discourse.slicer.org/c/community/vmtk
