### ISSUE TITLE
MAPPING AND PATCHING problem

### ISSUE THREAD

**Issue by junqiangchen** [vmtk/vmtk#368]
hi,
i try the MAPPING AND PATCHING example from here,http://www.vmtk.org/tutorials/MappingAndPatching.html,i input my stl sruface file,step by step with the longitudinalpatchsize and circularpatches just same with the example,i can get the result,but the result have missing some part.
![原始stl](https://user-images.githubusercontent.com/28638716/122554880-1b6b6300-d06c-11eb-9f7f-44e2e686405a.PNG)
![应力分析](https://user-images.githubusercontent.com/28638716/122554883-1c03f980-d06c-11eb-88b9-76791d94537a.PNG)
can you tell me how to solve the problem or maybe the params are not suitable, can you tell me how to set?
thank you!!

chenjunqiang

**Comment by alexluuuu** [comment]
Have you confirmed the integrity of your centerlines? Maybe if you are not able to generate a continuous centerline due to the geometry at what looks like the iliac bifurcation, you may not be able to extend the surface analysis further down.

**Comment by junqiangchen** [comment]
> Have you confirmed the integrity of your centerlines? Maybe if you are not able to generate a continuous centerline due to the geometry at what looks like the iliac bifurcation, you may not be able to extend the surface analysis further down.

i have checked the centerlines,there is no problem,and can get right mapping result,but the patching result is wrong.
![捕获](https://user-images.githubusercontent.com/28638716/123236355-4f80d100-d50f-11eb-8dce-daec7ef687d1.PNG)
![捕获2](https://user-images.githubusercontent.com/28638716/123236362-50b1fe00-d50f-11eb-9cd3-6da62d440b7e.PNG)
![捕获3](https://user-images.githubusercontent.com/28638716/123236372-527bc180-d50f-11eb-867d-9f667a1ef46d.PNG)
i don't know how to fix it?
thank you

chenjunqiang

**Comment by alexluuuu** [comment]
It seems to me that it is because of the bifurcation of the centerlines here. Can you try seeing what will happen if you follow the instructions for specifying a specific GroupID, as in the example for "Extraction of One Branch"?

**Comment by junqiangchen** [comment]
> It seems to me that it is because of the bifurcation of the centerlines here. Can you try seeing what will happen if you follow the instructions for specifying a specific GroupID, as in the example for "Extraction of One Branch"?

I use one branch centerline for test,and get null result.but i change another surface stl,can get mapping and patching result.
![1](https://user-images.githubusercontent.com/28638716/123353539-4f76e480-d594-11eb-8a9e-0853c5e9e850.PNG)
![mapping](https://user-images.githubusercontent.com/28638716/123353544-5140a800-d594-11eb-9b8e-089bf682a974.PNG)
![patching](https://user-images.githubusercontent.com/28638716/123353545-5271d500-d594-11eb-89e9-f24ad4b73d82.PNG)
so,i use above stl try again,and show vtk message window,maybe the reason is that branch vessel is not cylindrical.
![错误信息](https://user-images.githubusercontent.com/28638716/123353667-96fd7080-d594-11eb-807a-4e9c28ecb653.PNG)
 is there any methods for post-processing optimizing stl making analyse more easily.
thank you

**Comment by alexluuuu** [comment]
It seems that your initial STL had some islands near the bifurcation. You can see them being mapped to the red branch in the previous attached photos. I cannot tell if these island structures are due to your STL not being a closed cylinder or if it is because VMTK cannot handle the island patches. 

If you are trying to post-process your STL to remove islands, you can try reading it using something like pyvista or python VTK. You can use the VTK filter (or the Pyvista wrapped version) that identifies islands and keep only the largest island. 

I believe there are numerous other methods to check whether your STL surface is closed.

**Comment by junqiangchen** [comment]
> It seems that your initial STL had some islands near the bifurcation. You can see them being mapped to the red branch in the previous attached photos. I cannot tell if these island structures are due to your STL not being a closed cylinder or if it is because VMTK cannot handle the island patches.
> 
> If you are trying to post-process your STL to remove islands, you can try reading it using something like pyvista or python VTK. You can use the VTK filter (or the Pyvista wrapped version) that identifies islands and keep only the largest island.
> 
> I believe there are numerous other methods to check whether your STL surface is closed.

thank you alexluuu，i will try

**Comment by estamos** [comment]
Hello,

I am currently facing a similar issue so I thought it may be a good place to ask for possible solutions and insights.

I am as well working on a study based on [Mapping and Patching](http://www.vmtk.org/tutorials/MappingAndPatching.html) tutorial on vmtk.
Centerlines are created correctly and bifurcation seems to be fine as you can see at screenshots below. Abscissa metric looks normal as well.

> Centerlines and reference systems

![centerlines_and_reference_systems](https://github.com/user-attachments/assets/3c209f22-81ae-42a2-bce9-d327d63cf337)

> groupIDs
![groupIDs](https://github.com/user-attachments/assets/9184cff7-b792-4a15-9d13-444cd999d0be)

> Abscissa metric
![abscissa_metric](https://github.com/user-attachments/assets/bda73f5a-972c-43c3-a515-f5e3a0041ccd)


However, when running`vmtkbranchmapping` I receive the following error:
```
Executing vmtkbranchmapping ...
Computing boundary metric
ERROR: In ../vtkVmtk/ComputationalGeometry/vtkvmtkPolyDataReferenceSystemBoundaryMetricFilter.cxx, line 288
vtkvmtkPolyDataReferenceSystemBoundaryMetricFilter (0x6000013d8000): Branch is not topologically a cylinder

Computing harmonic mapping
Warning: In ../vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataCylinderHarmonicMappingFilter.cxx, line 67
vtkvmtkPolyDataCylinderHarmonicMappingFilter (0x600001fd0160): Input poly data is not topologically a cylinder.

Warning: In ../vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataCylinderHarmonicMappingFilter.cxx, line 67
vtkvmtkPolyDataCylinderHarmonicMappingFilter (0x600001fcc000): Input poly data is not topologically a cylinder.

Warning: In ../vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataCylinderHarmonicMappingFilter.cxx, line 67
vtkvmtkPolyDataCylinderHarmonicMappingFilter (0x600001fd40b0): Input poly data is not topologically a cylinder.

0 : 2.0182472825e+04 -- 2.0182472825e-08
100 : 2.6718585805e-03 -- 2.0182472825e-08
200 : 6.4897907905e-08 -- 2.0182472825e-08
in OpenNL : ||Ax-b||/||b|| = 9.390982e-07
Warning: In ../vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataCylinderHarmonicMappingFilter.cxx, line 67
vtkvmtkPolyDataCylinderHarmonicMappingFilter (0x600001fdcc60): Input poly data is not topologically a cylinder.

Warning: In ../vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataCylinderHarmonicMappingFilter.cxx, line 67
vtkvmtkPolyDataCylinderHarmonicMappingFilter (0x600001fcc000): Input poly data is not topologically a cylinder.

Stretching harmonic mapping
ERROR: In ../vtkVmtk/ComputationalGeometry/vtkvmtkPolyDataStretchMappingFilter.cxx, line 218
vtkvmtkPolyDataStretchMappingFilter (0x600001dc8000): Branch not topologically a cylinder.

Done executing vmtkbranchmapping.
Writing VTK XML surface file.
Output vmtkbranchmapping members:
    Id = 0
    Surface = vtkPolyData
    HarmonicMappingArrayName = HarmonicMapping
    BoundaryMetricArrayName = BoundaryMetric
    StretchedMappingArrayName = StretchedMapping
```
> Harmonic mapping error
![harmonic_mapping_error](https://github.com/user-attachments/assets/3201dd1d-f2fa-48ba-a63c-205f7656f9da)

I have identified the points at code where the errors and warning occured.

1. [vtkvmtkPolyDataReferenceSystemBoundaryMetricFilter.cxx](https://github.com/vmtk/vmtk/blob/master/vtkVmtk/ComputationalGeometry/vtkvmtkPolyDataReferenceSystemBoundaryMetricFilter.cxx#L284)
2. [vtkvmtkPolyDataCylinderHarmonicMappingFilter.cxx](https://github.com/vmtk/vmtk/blob/6c189dd6ee644a466498bd382b0c19229f20daa5/vtkVmtk/DifferentialGeometry/vtkvmtkPolyDataCylinderHarmonicMappingFilter.cxx#L63)
3. [vtkvmtkPolyDataStretchMappingFilter.cxx](https://github.com/vmtk/vmtk/blob/6c189dd6ee644a466498bd382b0c19229f20daa5/vtkVmtk/ComputationalGeometry/vtkvmtkPolyDataStretchMappingFilter.cxx#L214)

`NumberOfCells` seems to be indeed 2 for each branch, so I it may not be a bug. 

@lassoan could have better knowledge of this. 

I have tried to use different geometry though, retrieving a few from [Vascular Model Repository](https://www.vascularmodel.com/) but I am still getting the same error.

> System Specs

OS: 15.0 (24A335)
vmtk 1.4.0
conda 4.10.1
The commands I execute are the following:

```
vmtkcenterlines -ifile all_results_01893.vtp --pipe vmtkcenterlineattributes --pipe vmtkbranchextractor -ofile aorta_cl.vtp

vmtkbifurcationreferencesystems -ifile aorta_cl.vtp -radiusarray MaximumInscribedSphereRadius -blankingarray Blanking -groupidsarray GroupIds -ofile aorta_cl_rs.vtp

vmtkbranchclipper -ifile all_results_01893.vtp -centerlinesfile aorta_cl.vtp -groupidsarray GroupIds -radiusarray MaximumInscribedSphereRadius -blankingarray Blanking -ofile aorta_clipped.vtp

vmtkbranchmetrics -ifile aorta_clipped.vtp -centerlinesfile aorta_cl.vtp -abscissasarray Abscissas -normalsarray ParallelTransportNormals -groupidsarray GroupIds -centerlineidsarray CenterlineIds -tractidsarray TractIds -blankingarray Blanking -radiusarray MaximumInscribedSphereRadius -ofile aorta_clipped_metrics.vtp

vmtkbranchmapping -ifile aorta_clipped_metrics.vtp -centerlinesfile aorta_cl.vtp -referencesystemsfile aorta_cl_rs.vtp -normalsarray ParallelTransportNormals -abscissasarray Abscissas -groupidsarray GroupIds -centerlineidsarray CenterlineIds -tractidsarray TractIds -referencesystemsnormalarray Normal -radiusarray MaximumInscribedSphereRadius -blankingarray Blanking -angularmetricarray AngularMetric -harmonicmappingarray HarmonicMapping -abscissametricarray AbscissaMetric -ofile aorta_clipped_mapping.vtp

```

Any insight would be highly appreciated, thank you.
