### ISSUE TITLE
how to generate multiple mesh files with different time steps

### ISSUE THREAD

**Issue by junqiangchen** [vmtk/vmtk#369]
Hi,
than you for sharing the PARTICLE TRACING example with vmtk,i have problem that how to generate different timestep meshs,can anyone share some example code or tools how to use it generate different timestep meshes?
best wishes!!
chenjunqiang

**Comment by lassoan** [comment]
Could you please post your question to the [VMTK forum](https://discourse.slicer.org/c/community/vmtk)?

We would like to use this issue tracker to track problems and plan enhancement ideas.
