### ISSUE TITLE
 How to execute the MPR image by vmtkimagecurvedmpr？

### ISSUE THREAD

**Issue by zs901003** [vmtk/vmtk#370]
I use this scripts to execute the MPR image, the input file format is vti, the output file format is vtp, the centerlines file is executed by other scrips of vmtk, but the output image size is 1k?  Why output is so small?

**Comment by lassoan** [comment]
Could you please post your question to the [VMTK forum](https://discourse.slicer.org/c/community/vmtk)?

We would like to use this issue tracker to track problems and plan enhancement ideas.

**Comment by zs901003** [comment]
OK, thank you very much
