### ISSUE TITLE
How to process large number of image with vmtklevesetsegmentation without using interactive inputs

### ISSUE THREAD

**Issue by DongweiYe** [vmtk/vmtk#371]
Hi,

I am currently using vmtk to process my large image dataset. For each image I need to use `vmtklevelsetsegmentation` to process the image interactively, using the threshold method and set upper and lower thresholds, etc.... 

However, I have thousands of images to deal with and it is impossible to handle all of them manually. I wanna ask if there is a way to set all the parameters of `vmtklevelsetsegmentation` as part of the command line or script so I can just run a shell script file to let it execute by itself?

Thank you!

**Comment by lassoan** [comment]
Could you please post your question to the [VMTK forum](https://discourse.slicer.org/c/community/vmtk)?

We would like to use this issue tracker to track problems and plan enhancement ideas.
