### ISSUE TITLE
volume mesh

### ISSUE THREAD

**Issue by amberhappy** [vmtk/vmtk#374]
hi, I stucked there for hours when running volume mesh:
 "TetGen command line options: pq1.414000q10.000000q165.000000YsT1.000000e-08zQm"
![image](https://user-images.githubusercontent.com/20748171/126124575-3ec72083-727a-4d2c-ae68-366d0c11552f.png)

**Comment by amberhappy** [comment]
On macOs, python 3.6.1, vmtk 1.4.0
![image](https://user-images.githubusercontent.com/20748171/126124729-18a63e38-9167-4b40-9c7e-028bee9c2fb0.png)

**Comment by lassoan** [comment]
Tetgen is not a very stable software. If it crashes or hangs you can try improving the quality of the input mesh or change the meshing parameters.

**Comment by amberhappy** [comment]
Thank you so much, I add several meshing parameters, and it now works well.
