### ISSUE TITLE
problem with python wrappings: vtkvmtkSegmentationPython, vtkvmtkITKPython import

### ISSUE THREAD

**Issue by sbugenha** [vmtk/vmtk#379]
I compiled VMTK from git and my python paths are set correctly. I can import vtk, itk, and vmtk without issues. However, importing vtkvmtk results in import errors as follows for vtkvmtkSegmentationPython and vtkvmtkITKPython:

"ImportError: DLL load failed: The specified module could not be found."

All but the following lines in the below vtkvmtk.py file work. I saw this issue raised previously (see <https://vmtk-users.narkive.com/8mIDMzuE/problem-with-python-wrappings-vtkvmtksegmentationpython-vtkvmtkitkpython-import>) but don't think I ever saw a solution. Just wondering if there is any known fix.

Thanks,

Scott

#!/usr/bin/env python
""" This module loads all the classes from the vtkVmtk library into its
namespace.  This is a required module."""

from __future__ import absolute_import #NEEDS TO STAY AS TOP LEVEL MODULE FOR Py2-3 COMPATIBILITY
import os
import vtk

from .vtkvmtkCommonPython import *
from .vtkvmtkComputationalGeometryPython import *
from .vtkvmtkDifferentialGeometryPython import *
from .vtkvmtkIOPython import *
from .vtkvmtkMiscPython import *
try:
  from .vtkvmtkRenderingPython import *
except:
  pass
==>from .vtkvmtkSegmentationPython import *
==>from .vtkvmtkITKPython import *
try:
  from .vtkvmtkContribPython import *
except:
  pass

**Comment by lassoan** [comment]
You can find which DLL is missing in the Windows event log, using Dependency Walker, or using sxstrace. Most likely that will make it obvious what is wrong.

If you are using VTK9 then we may be able to help you when VMTK build system upgrade to VTK9 is completed (see https://github.com/vmtk/vmtk/pull/372). If you are using an older VTK version or Python2 then most likely you'll need to find a solution to your problem yourself.

**Comment by sbugenha** [comment]
Hi Andras,

Thank you very much for your tip - Dependency Walker worked like a charm! The problem was that the location of the DLLs of VTK and ITK weren't on the search path so VMTK wasn't finding them. 

I am currently using VTK 8.1 and ITK 4.13 with Python 3.7 on Windows 10. After fixing the problem above, everything seems to work fine, but I will do some more tests to verify. I'm looking forward to the VMTK build upgrade with VTK9! I plan to switch over when it's ready.

Thanks,
Scott
