### ISSUE TITLE
Low efficiency of center line extraction

### ISSUE THREAD

**Issue by J-J-Wang** [vmtk/vmtk#380]
After I read in the data(.stl), I process it with  **vtkDecimatePro**,but when I ty to improve digital of function  **vtkDecimatePro::SetTargetReduction( digital )**.I got error _:vtkvmtkPolyDataBoundaryExtractor.cxx, line 194
vtkvmtkPolyDataBoundaryExtractor (00000249D0FFBB60): Can't find adjacent point. Bailing out._   

At the same time, I find that the efficiency of vtkDelaunay3D segmentation is very low. For large models, the processing time is even more than 1 minute. Do you have any good suggestions?

**Comment by lassoan** [comment]
vtkDecimatePro is known to damage geometry at high reduction rates. You can use FastQuadric decimation instead.

I would recommend trying 3D Slicer's Extract Centerline module, as it has adaptive decimation, automatic centerline endpoint extraction, convenient GUI to add/remove/edit centerline endpoints, and you can use many other tools in 3D Slicer and its built-in Python interpreter to do lots of visualization and analysis.
