### ISSUE TITLE
ITK 5+ compatibility

### ISSUE THREAD

**Issue by deniskristak** [vmtk/vmtk#381]
Hello,
I'm running into problems installing `vmtk` with `ITK 5.1.2.`
I'm using latest official release of `vmtk` - version 1.4.0, which I see is from 2018.

Some of errors:

> /tmp/vsc43810/easybuild/build/VMTK/1.4.0/foss-2020a-Python-3.8.2/vmtk-1.4.0/vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKArchetypeImageSeriesReader.cxx:679:63: error: UCHAR is not a member of itk::ImageIOBase
  679 |         if ( imageIO->GetComponentType() == itk::ImageIOBase::UCHAR )
      |                                                               ^~~~~
/tmp/vsc43810/easybuild/build/VMTK/1.4.0/foss-2020a-Python-3.8.2/vmtk-1.4.0/vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKArchetypeImageSeriesReader.cxx:684:63: error: CHAR is not a member of itk::ImageIOBase
  684 |         if ( imageIO->GetComponentType() == itk::ImageIOBase::CHAR )
      |                                                               ^~~~
/tmp/vsc43810/easybuild/build/VMTK/1.4.0/foss-2020a-Python-3.8.2/vmtk-1.4.0/vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKArchetypeImageSeriesReader.cxx:689:63: error: USHORT is not a member of itk::ImageIOBase
  689 |         if ( imageIO->GetComponentType() == itk::ImageIOBase::USHORT )
      |                                                               ^~~~~~

Seems like those errors are caused by `ITK` upgrade from 4.x to 5.x -  [more info](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md).

I see that in [installation guide](http://www.vmtk.org/download/), you recommend using `ITK 4.13`. Is this a given, isn't there, by any chance, a newer version or commit which supports installation with `ITK` 5+?

Also, would you generally recommend using some of the newer commits / is a new official release due anytime soon?

Thank you for your answers!

**Comment by lassoan** [comment]
We have made VMTK compatible with ITK 5.2 and VTK 9.1 in this branch that we plan to merge soon: https://github.com/vmtk/vmtk/pull/372

**Comment by deniskristak** [comment]
thanks, I'll stick to that branch then :-)

**Comment by deniskristak** [comment]
@lassoan think im running into the same problems as mentioned in [this comment](https://github.com/vmtk/vmtk/pull/372#issuecomment-888451876)

guess i'll wait until you guys finish working on that, will use older ITK for now

**Comment by lassoan** [comment]
We already use ITK 5.2 already with this VMTK version. We don't use vtkvmtkITKArchetypeImageSeriesReader though, and you don't need it either, you can use standard ITK image readers instead.

**Comment by deniskristak** [comment]
@lassoan can you please give me configuration flags (or where to look for them) which will help me achieve that?
thank you very much

**Comment by lassoan** [comment]
See the build options that we use here: https://github.com/vmtk/SlicerExtension-VMTK/blob/master/SuperBuild/External_VMTK.cmake

**Comment by kayarre** [comment]
This issue should be resolved by #372.
