### ISSUE TITLE
vmtkflowextensions

### ISSUE THREAD

**Issue by AmyVermeer** [vmtk/vmtk#384]
I am using vmtkflowextensions to add short flow extensions to the inlet and outlets of my 3D model.  In the attached screencapture it can be seen that the flow extension does not fit nicely to the domain.
![image](https://user-images.githubusercontent.com/45363168/133105360-de5cf630-8a4f-4101-bf45-f3b1aa22dd8b.png)

vmtksurfacereader -ifile inputfile --pipe vmtkcenterlines -seedselector openprofiles --pipe vmtkflowextensions -extensionratio 2 -normalestimationratio 1 -ofile ouptutfile

I am using the above line of code. Where does the problem with the flow extension come from?

**Comment by lassoan** [comment]
To discuss questions about how to use VMTK, please post them to the [VMTK forum](https://discourse.slicer.org/c/community/vmtk/28).
