### ISSUE TITLE
Reconstruct Mesh from a custom centerline

### ISSUE THREAD

**Issue by Paddy-Xu** [vmtk/vmtk#417]
Hi,

Thanks for the very valuable repository. I am wondering if it is possible to generate the tubular mesh based on a synthetically generated centerline with bifurcation? 

So what I have is a graph/tree structure with nodes indicating each point along the centerlines with radius at each point, as well as edges indicating the connectivity of each point, but what I do not have is the Voronoi diagram. 

Is it possible to reconstruct the surface/volume mesh from such centerlines using this tool?

Thanks a lot in advance!

**Comment by lassoan** [comment]
Github issues are for tracking problems and their resolutions. Please ask questions about VMTK at https://discourse.slicer.org/c/community/vmtk/
