### ISSUE TITLE
vtkvmtkITKImageToImageFilterFF related file missing

### ISSUE THREAD

**Issue by fgbxx** [vmtk/vmtk#418]
hi, developer 
   when I use the class VTK_VMTK_SEGMENTATION_EXPORT vtkvmtkVesselEnhancingDiffusion3DImageFilter : public vtkvmtkITKImageToImageFilterFF,
   There is info that can not find vtkvmtkITKImageToImageFilterFF, so mean the fililter can not be used ever?

Best,
Gang

**Comment by ramtingh** [comment]
That file was deleted 7 years ago in https://github.com/vmtk/vmtk/commit/b7845bebf59aab5ef0e2669c18cb019d4ee23c17 
Presumably the intention is to use vtkvmtkVesselEnhancingDiffusionImageFilter rather than vtkvmtkVesselEnhancingDiffusion3DImageFilter, it should handle 3D volumes

**Comment by fgbxx** [comment]
Thank you  so much!
