### ISSUE TITLE
VMTK installation - error git clone vtk

### ISSUE THREAD

**Issue by TechnoFx** [vmtk/vmtk#429]
Hello, 

I am trying to build vmtk by following this tutorial : http://www.vmtk.org/download/ (development version part).

I have this error : 

![image](https://user-images.githubusercontent.com/65617651/169273242-10647709-b5d3-4144-b8f7-eafa92a162f6.png)

I don't know what to do since the command for cloning the VTK repo : git clone https://github.com/Kitware/VTK.git is working.

Thank you for your help,

Ubuntu : 20.04
Cmake version : 3.16
Make version : GNU Make 4.2.1

**Comment by TechnoFx** [comment]
I manage to make it works by going in the file 'VTK-gitclone.cmake'  in /home/user-name/vmtk/vmtk-build/tmp/VTK  and modifying on ligne 20 'git' par 'https' so as to have : `l.20 = COMMAND "/usr/bin/git"  clone --no-checkout "https://github.com/Kitware/VTK.git" "VTK"`

**Comment by bobcieri** [comment]
I am now getting a similar issue. Trying to build VMTK from the git clone on MacOS 11.7.10 and it fails in building VTK with a similar error:

Cloning into 'VTK'...
error: RPC failed; curl 18 HTTP/2 stream 3 was reset
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'VTK'...
error: RPC failed; curl 18 HTTP/2 stream 3 was reset
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'VTK'...
error: RPC failed; curl 18 HTTP/2 stream 3 was reset
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
-- Had to git clone more than once:
          3 times.
CMake Error at tmp/VTK/VTK-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/Kitware/VTK.git'
