### ISSUE TITLE
Problem with centerlines

### ISSUE THREAD

**Issue by andrzejjaeschke** [vmtk/vmtk#433]
Hi!

I've been using vmtk centerlines for a while. It generally works well for most of my models. But sometimes I get the error:
ERROR: In D:\bld\vmtk_1651749973752\work\vtkVmtk\ComputationalGeometry\vtkvmtkSteepestDescentLineTracer.cxx, line 349
vtkvmtkSteepestDescentLineTracer (0000021C2A7559B0): Seed id invalid or exceeds input number of points.

I'm calling the procedure from pypes with the following command:
"mtksurfacereader -ifile "path_to_stl" --pipe vmtkcenterlines -endpoints 1 -seedselector openprofiles -sourceids 1 -ofile "output_path" --pipe vmtkrenderer --pipe vmtksurfaceviewer -opacity 0.25 --pipe vmtksurfaceviewer -i @vmtkcenterlines.o -array MaximumInscribedSphereRadius'

It fails in particular for the attached zipped stl.
And the problem is with the path to the thinnest outflow.
Do you have an idea why this can happen? The error is a bit enigmatic. 

[Walls_out2.zip](https://github.com/vmtk/vmtk/files/9072815/Walls_out2.zip)

**Comment by ramtingh** [comment]
Your mesh is in unit of meters, whereas vmtk (and particularly the centerline calculation, which is specially finicky) assumes milimetres. 
![image](https://user-images.githubusercontent.com/1287898/178022967-697300a4-8568-4b0d-9007-89ddaa5f0fac.png)

**Comment by ramtingh** [comment]
Firstly you'd probably have less headaches using Slicer's centerline extraction module (built on top of vmtk), however if you want to continue using vmtkcenterlines directly you should scale the mesh before passing to vmtkcenterlines and then scale it back to meters, which is what I used for the above figure:
```vmtksurfacescaling.py -ifile Walls_out2.stl -scale 1000 --pipe vmtkcenterlines -seedselector openprofiles -endpoints 1 --pipe vmtksurfacescaling -scale 0.001 -i @.o -ofile ctr.vtp```

(Or switch everything else you're doing to work in milimeters)

**Comment by andrzejjaeschke** [comment]
Thank you! Works like a charm.
