### ISSUE TITLE
VMTK error: eroor when executing vmtkcenterlines

### ISSUE THREAD

**Issue by gboels** [vmtk/vmtk#440]
Hi all, 

I get this error when trying to calculate a centerline:
![image](https://user-images.githubusercontent.com/116432295/197332745-9352f412-b39d-41c9-a672-9cb0a4cff5f0.png)

Can someone help me with this?

Thanks in advance!

**Comment by lassoan** [comment]
VMTK's very limited built-in interaction and visualization tools are not maintained anymore, therefore when the underlying visualization toolkit (VTK) changes, it can result in error like this. You have several options:
- Use 3D Slicer's VMTK extension if you need a rich, convenient graphical user interface for VMTK.
- Update the failing VMTK Python scripts to work with recent VTK versions.
- Only use VMTK's processing features and take care of getting user inputs and displaying result in alternative ways (juse plain Python scripts, VTK, 3D Slicer, ParaView, etc.).

I'm closing this issue, as we don't plan to work on this. If you provide a pull request with a fix then we'll accept it.
