### ISSUE TITLE
Couldn't resolve host name

### ISSUE THREAD

**Issue by axjing** [vmtk/vmtk#442]
CMake Error at CMake/CMakeLists.txt:23 (file):
  file DOWNLOAD HASH mismatch

    for file: [E:/Library/VtkVmtk/CMake/vtkMacroKitPythonWrap.cmake]
      expected hash: [4470613601f97d36221a7af072731475d06f03d4eb19f550d230bc468264088b]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [6;"Couldn't resolve host name"]

CMake Error at CMake/CMakeLists.txt:23 (file):
  file DOWNLOAD HASH mismatch

    for file: [E:/Library/VtkVmtk/CMake/vtkWrapHierarchy.cmake]
      expected hash: [ca3ea938ae7eb7c94da8a99d1c45556de5c0562ab91f7b2a5c5640e50f005a88]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [6;"Couldn't resolve host name"]

CMake Error at CMake/CMakeLists.txt:23 (file):
  file DOWNLOAD HASH mismatch

    for file: [E:/Library/VtkVmtk/CMake/vtkWrapPython.cmake]
      expected hash: [4bdd1adcd02b7db393c32ae902f208389fb80141584e5b68f7668dd379f62134]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [6;"Couldn't resolve host name"]

CMake Error at CMake/CMakeLists.txt:23 (file):
  file DOWNLOAD HASH mismatch

    for file: [E:/Library/VtkVmtk/CMake/vtkWrapperInit.data.in]
      expected hash: [3e840679603eb4a0d425c1244828729cb271f33a081c5ac2e0547aa747bbec5d]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [6;"Couldn't resolve host name"]

**Comment by zsp1993** [comment]
hello，I am also facing this problem，have you resolve it?

**Comment by lassoan** [comment]
You are either behind a firewall that blocks network access or you are using an old VMTK version that refers to some URLs that are not valid anymore.

Since current VMTK version does not even have CMake/vtkWrapPython.cmake, we will not investigate this. Please submit an issue if you have problems with more recent VMTK versions.
