### ISSUE TITLE
ERROE occurs in Performing configure step for 'VMTK' 

### ISSUE THREAD

**Issue by mengzhelyu** [vmtk/vmtk#451]
CMake Warning:
  Ignoring extra path from command line:

   "/home/jamie/vmtk-master/build/VMTK-Build/@rpath"

CMake Error at CMake/vmtkFunctions.cmake:7 (include):
  include could not find requested file:

    vtkMacroKitPythonWrap
Call Stack (most recent call first):
  vtkVmtk/CMakeLists.txt:11 (include)

CMake Warning (dev) at /usr/local/share/cmake-3.25/Modules/Documentation.cmake:30 (message):
  Policy CMP0106 is not set: The Documentation module is removed.  Run "cmake
  --help-policy CMP0106" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  Documentation.cmake is VTK-specific code and should not be used in non-VTK
  projects.  This logic in this module is best shipped with the project using
  it rather than with CMake.
Call Stack (most recent call first):
  vtkVmtk/Utilities/Doxygen/CMakeLists.txt:4 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMake/vmtkFunctions.cmake:90 (vtkMacroKitPythonWrap):
  Unknown CMake command "vtkMacroKitPythonWrap".
Call Stack (most recent call first):
  vtkVmtk/Utilities/vtkvmtkITK/CMakeLists.txt:40 (vmtk_build_library)

-- Configuring incomplete, errors occurred!
See also "/home/jamie/vmtk-master/build/VMTK-Build/CMakeFiles/CMakeOutput.log".
CMakeFiles/VMTK.dir/build.make:92: recipe for target 'Stamp/VMTK/VMTK-configure' failed
make[2]: *** [Stamp/VMTK/VMTK-configure] Error 1
CMakeFiles/Makefile2:139: recipe for target 'CMakeFiles/VMTK.dir/all' failed
make[1]: *** [CMakeFiles/VMTK.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Please help me with this error, i try to build ITK-4.13.0 and VTK-8.1.2.zip with vmtk-master but always stuck in this error.

**Comment by lassoan** [comment]
VTK 8 is no longer supported. You need to find an older VMTK version in the commit history that is compatible.
