### ISSUE TITLE
Request to join vcpkg

### ISSUE THREAD

**Issue by RainbowTaro2022** [vmtk/vmtk#455]
我已经在vcpkg里提交了请求，请你们这里也同意一下

**Comment by lassoan** [comment]
Message in English:

> I have submitted a request in vcpkg, please agree here

@RainbowTaro2022 the common language we all know and use for development of VMTK is English. Machine translation usually works well enough, but it is more respectful with everyone's time if you use a translator once instead requiring all readers to use a translator.

**Comment by lassoan** [comment]
VMTK uses CMake and ExternalProject to build dependencies and allow VMTK to be built as part of complex projects, so I don't think any developers have experience with vcpkg.

Pre-built libraries are less flexible (I guess you need to decide on using one specific set of build options), so I'm not sure if it is a very good way to distribute VMTK to C++ developers but having this as an additional option should not be a problem, as long as not a lot of maintenance effort is needed.

I have never submitted a vcpkg, so you need to guide us through the process. Please explain what you have done, what are the immediate next steps, and what responsibilities is we want to keep a functional and up-to-date VMTK package on vcpkg.

**Comment by RainbowTaro2022** [comment]
第一步，检查gitmodule，尝试把里面的项目提交到vcpkg里
第二步，检查cmake文件夹，有需要的话可以使用
第三步，提交到vcpkg，并检查问题

**Comment by RainbowTaro2022** [comment]
我向微软vcpkg项目提交了建议，但需要你们通过

**Comment by lassoan** [comment]
Please, as I asked above, keep discussion in English. I'll have to close this issue if we cannot effectively work together.

**Comment by RainbowTaro2022** [comment]
The first step is to check the gitmodule and try to submit the projects in it to vcpkg
Step 2, check the cmake folder and use it if necessary
Step 3, submit to vcpkg and check for issues

**Comment by RainbowTaro2022** [comment]
I have submitted a proposal to the Microsoft VCPKG project, but it requires your approval

**Comment by lassoan** [comment]
Can you give some more information about what was submitted and where? How the approval works?
Does the VMTK package work as is or some changes in the build system are needed?

**Comment by RainbowTaro2022** [comment]
I will review the required and required components of the module in detail in the vmtk project and let you know the results when I am done
