### ISSUE TITLE
vtkStandardNewMacro missing from vtkvmtkCenterlineSplittingAndGroupingFilter

### ISSUE THREAD

**Issue by nmontesg** [vmtk/vmtk#469]
VTK-style initialization of vtkvmtkCenterlineSplittingAndGroupingFilter fails to compile:

`vtkSmartPointer<vtkvmtkCenterlineSplittingAndGroupingFilter> filter = vtkSmartPointer<vtkvmtkCenterlineSplittingAndGroupingFilter>::New();`

Adding `vtkStandardNewMacro(vtkvmtkCenterlineSplittingAndGroupingFilter)` to vtkvmtkCenterlineSplittingAndGroupingFilter.cxx should fix the issue.

**Comment by lassoan** [comment]
Thanks for reporting this. Could you please submit a pull request with the proposed change?
