### ISSUE TITLE
Port to VTK 6

### ISSUE THREAD

**Issue by lantiga** [vmtk/vmtk#86]
http://www.vtk.org/Wiki/VTK/VTK_6_Migration_Guide

**Comment by lantiga** [comment]
Update: a lot of work for the C++ part has been done by @jcfr, see #133.
TODO: merge with work done previously this issue.

**Comment by leandrogryn** [comment]
Note: Contrib is not updated.

**Comment by lantiga** [comment]
Thanks, I'll look into it. We should be finalizing the VTK 6 port shortly.

**Comment by lantiga** [comment]
Contrib updated, Python scripts ported. We're almost there.
Two outstanding issues:
- vtkvmtkITK-based filters are not working, still have to track down why; best would be to convert all filters to what done for vtkvmtkSatoVesselnessMeasureImageFilter, which would allow to drop vtkvmtkITK (except for reader and writer).
- render window does not behave correctly on OSX ('q' will not close the window); Cocoa classes have been heavily refactored from VTK5.10 to VTK6, we need to understand how to port the vmtk code in Common to the new Cocoa code in VTK.

**Comment by lantiga** [comment]
- further Fixes to Python scripts done
- render window on OSX now works: one last thing to fix is modifier keys on image planes
- vtkvmtkITK-based filters are still not working

**Comment by lantiga** [comment]
The port is complete now, everything seems to be working at a first round of tests.
We'll test it further during the next few days, attack a few other issues and ideally release 1.3 in 2/3 weeks.

**Comment by lantiga** [comment]
vmtk master now builds with VTK 6.x and 7.0 rc
